force-app/main/default/objects/Default_Project_Team__c/Default_Project_Team__c.object-meta.xml
<CustomObject>
    <label>Default Project Team</label>
    <nameField>
        <displayFormat>DPTN-{00000000}</displayFormat>
        <label>Default Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Project Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_Project_Team__c/fields/Project_Access__c.field-meta.xml
<CustomField>
    <fullName>Project_Access__c</fullName>
    <label>Project Access</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Access</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Default_Project_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Default_Project_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Setting__c/User_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>User related settings - Enable defaulting of Project Team on Projects/Order Team on Orders.</description>
    <label>User - Setting</label>
</CustomObject>

force-app/main/default/globalValueSets/Project_Access.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Edit</fullName>
        <default>true</default>
        <label>Read/Write</label>
    </customValue>
    <customValue>
        <fullName>Read</fullName>
        <label>Read Only</label>
    </customValue>
    <masterLabel>Project Access</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EditDefaultProjectTeamController.cls
public class EditDefaultProjectTeamController
{
    public User user { get; set; }
    public User_Setting__c userSetting { get; set; }
    public Boolean updateProjectTeam { get; set; }
    public Default_Project_Team__c defaultProjectTeam { get; set; }
    
    public EditDefaultProjectTeamController(ApexPages.StandardController stdController)
    {
        defaultProjectTeam = (Default_Project_Team__c) stdController.getRecord();
        init();
    }
    
    public void init()
    {        
        defaultProjectTeam = [SELECT OwnerId, Project_Access__c, Team_Role__c, Team_Member__c, Team_Member__r.Name FROM Default_Project_Team__c WHERE Id = :defaultProjectTeam.Id];
        user = [SELECT Name FROM User WHERE Id = :defaultProjectTeam.OwnerId];
        userSetting = User_Setting__c.getInstance(user.Id);
        updateProjectTeam = false;
    }

    public PageReference save()
    {        
        List<Default_Project_Team__c> defaultProjectTeams = new List<Default_Project_Team__c>();
        defaultProjectTeams.add(defaultProjectTeam);
        boolean success = ProjectTeamController.createOrUpdateDefaultProjectTeam(defaultProjectTeams, user.Id, updateProjectTeam);
        if (success)
        {
        	upsert userSetting;   
        }
        return new PageReference('/' + userSetting.SetupOwnerId);
    }  
    
    public PageReference cancel()
    {		       
        return new PageReference('/' + userSetting.SetupOwnerId);
    }
}