force-app/main/default/objects/Default_Project_Team__c/Default_Project_Team__c.object-meta.xml
<CustomObject>
    <label>Default Project Team</label>
    <nameField>
        <displayFormat>DPTN-{00000000}</displayFormat>
        <label>Default Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Project Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_Project_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Default_Project_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <label>Project Team</label>
    <nameField>
        <displayFormat>PJT-{0000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Teams</relationshipLabel>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeleteDefaultProjectTeamController.cls
public class DeleteDefaultProjectTeamController 
{
    public User user { get; set; }    
    public Boolean deleteProjectTeam { get; set; }
    public Default_Project_Team__c defaultProjectTeam { get; set; }
    
    public DeleteDefaultProjectTeamController(ApexPages.StandardController stdController)
    {
        defaultProjectTeam = (Default_Project_Team__c) stdController.getRecord();
        init();
    }
    
    public void init()
    {                
        defaultProjectTeam = [SELECT OwnerId, Team_Member__c FROM Default_Project_Team__c WHERE Id =:defaultProjectTeam.Id];
        user = [SELECT Name FROM User WHERE Id = :defaultProjectTeam.OwnerId];        
        deleteProjectTeam = false;
    }

    public PageReference deleteRecord()
    {        
        if (deleteProjectTeam == true)
        {
            List<Project__c> ownedProjects = [SELECT Id, (SELECT Team_Member__c FROM Project_Teams__r WHERE Team_Member__c = :defaultProjectTeam.Team_Member__c) FROM Project__c WHERE OwnerId =: user.Id];            
            List<Project_Team__c> existingProjectTeams = new List<Project_Team__c>();            
            for (Project__c ownedProject : ownedProjects)
            {      
                for (Project_Team__c existingProjectTeam : ownedProject.Project_Teams__r)
                {                                           
                    existingProjectTeams.add(existingProjectTeam);                        
                }
            } 
            delete existingProjectTeams;
        }
        delete defaultProjectTeam;        
        return new PageReference('/' + user.Id);
    }  
    
    public PageReference cancel()
    {		       
        return new PageReference('/' + user.Id);
    }
}