force-app/main/default/objects/Default_Lead_Team__c/Default_Lead_Team__c.object-meta.xml
<CustomObject>
    <label>Default Lead Team</label>
    <nameField>
        <displayFormat>DLTN-{00000000}</displayFormat>
        <label>Default Lead Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Lead Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_Lead_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Default_Lead_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_Lead_Team__c/fields/Team_Role__c.field-meta.xml
<CustomField>
    <fullName>Team_Role__c</fullName>
    <label>Team Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Team_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Setting__c/User_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>User related settings - Enable defaulting of Project Team on Projects/Order Team on Orders.</description>
    <label>User - Setting</label>
</CustomObject>

force-app/main/default/globalValueSets/Lead_Team_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Executive Sponsor</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Qualifier</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Sales Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Rep</fullName>
    </customValue>
    <masterLabel>Lead Team Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EditDefaultLeadTeamController.cls
public class EditDefaultLeadTeamController
{
    public User user { get; set; }
    public User_Setting__c userSetting { get; set; }
    public Boolean updateLeadTeam { get; set; }
    public Default_Lead_Team__c defaultLeadTeam { get; set; }
    
    public EditDefaultLeadTeamController(ApexPages.StandardController stdController)
    {
        defaultLeadTeam = (Default_Lead_Team__c) stdController.getRecord();
        init();
    }
    
    public void init()
    {        
        defaultLeadTeam = [SELECT OwnerId, Lead_Access__c, Team_Role__c, Team_Member__c, Team_Member__r.Name FROM Default_Lead_Team__c WHERE Id = :defaultLeadTeam.Id];
        user = [SELECT Name FROM User WHERE Id = :defaultLeadTeam.OwnerId];
        userSetting = User_Setting__c.getInstance(user.Id);
        updateLeadTeam = false;
    }

    public PageReference save()
    {        
        List<Default_Lead_Team__c> defaultLeadTeams = new List<Default_Lead_Team__c>();
        defaultLeadTeams.add(defaultLeadTeam);
        boolean success = LeadTeamController.createOrUpdateDefaultLeadTeam(defaultLeadTeams, user.Id, updateLeadTeam);
        if (success)
        {
        	upsert userSetting;   
        }
        return new PageReference('/' + userSetting.SetupOwnerId);
    }  
    
    public PageReference cancel()
    {		       
        return new PageReference('/' + userSetting.SetupOwnerId);
    }
}