force-app/main/default/objects/Default_Lead_Team__c/Default_Lead_Team__c.object-meta.xml
<CustomObject>
    <label>Default Lead Team</label>
    <nameField>
        <displayFormat>DLTN-{00000000}</displayFormat>
        <label>Default Lead Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Lead Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_Lead_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Default_Lead_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Team__c/Lead_Team__c.object-meta.xml
<CustomObject>
    <label>Lead Team</label>
    <nameField>
        <displayFormat>LET-{0000}</displayFormat>
        <label>Lead Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeleteDefaultLeadTeamController.cls
public class DeleteDefaultLeadTeamController 
{
    public User user { get; set; }    
    public Boolean deleteLeadTeam { get; set; }
    public Default_Lead_Team__c defaultLeadTeam { get; set; }
    
    public DeleteDefaultLeadTeamController(ApexPages.StandardController stdController)
    {
        defaultLeadTeam = (Default_Lead_Team__c) stdController.getRecord();
        init();
    }
    
    public void init()
    {                
        defaultLeadTeam = [SELECT OwnerId, Team_Member__c FROM Default_Lead_Team__c WHERE Id =:defaultLeadTeam.Id];
        user = [SELECT Name FROM User WHERE Id = :defaultLeadTeam.OwnerId];        
        deleteLeadTeam = false;
    }

    public PageReference deleteRecord()
    {        
        if (deleteLeadTeam == true)
        {
            List<Lead> ownedLeads = [SELECT Id, (SELECT Team_Member__c FROM Lead_Teams__r WHERE Team_Member__c = :defaultLeadTeam.Team_Member__c) FROM Lead WHERE OwnerId =: user.Id];            
            List<Lead_Team__c> existingLeadTeams = new List<Lead_Team__c>();            
            for (Lead ownedLead : ownedLeads)
            {      
                for (Lead_Team__c existingLeadTeam : ownedLead.Lead_Teams__r)
                {                                           
                    existingLeadTeams.add(existingLeadTeam);                        
                }
            } 
            delete existingLeadTeams;
        }
        delete defaultLeadTeam;        
        return new PageReference('/' + user.Id);
    }  
    
    public PageReference cancel()
    {		       
        return new PageReference('/' + user.Id);
    }
}