force-app/main/default/objects/Default_Lead_Team__c/Default_Lead_Team__c.object-meta.xml
<CustomObject>
    <label>Default Lead Team</label>
    <nameField>
        <displayFormat>DLTN-{00000000}</displayFormat>
        <label>Default Lead Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Lead Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_Lead_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Default_Lead_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_Lead_Team__c/fields/Team_Role__c.field-meta.xml
<CustomField>
    <fullName>Team_Role__c</fullName>
    <label>Team Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Team_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Team__c/Lead_Team__c.object-meta.xml
<CustomObject>
    <label>Lead Team</label>
    <nameField>
        <displayFormat>LET-{0000}</displayFormat>
        <label>Lead Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Team__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Team</relationshipLabel>
    <relationshipName>Lead_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Team__c/fields/Lead_Access__c.field-meta.xml
<CustomField>
    <fullName>Lead_Access__c</fullName>
    <label>Lead Access</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Access</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Lead_Access.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Edit</fullName>
        <default>true</default>
        <label>Read/Write</label>
    </customValue>
    <customValue>
        <fullName>Read</fullName>
        <label>Read Only</label>
    </customValue>
    <masterLabel>Lead Access</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lead_Team_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Executive Sponsor</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Qualifier</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Sales Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Rep</fullName>
    </customValue>
    <masterLabel>Lead Team Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadTeamTest.cls
@isTest
public class LeadTeamTest 
{
	static final String TEST_USERNAME = 'testuser@mail.weir.invalid';    
    static final String LEAD_NAME = 'Test';
    static final String SHARING_REASON = 'Manual';
    static final String TEAM_ACCESS_EDIT = 'Edit';
    static final String TEAM_ROLE_ACCOUNT_MANAGER = 'Account Manager';
    static final String TEAM_ROLE_CHANNEL_MANAGER = 'Channel Manager';
    
    @testSetup
    static void setupData()
    {
        Profile profile = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User user = new User(Alias = 'standt', Email='standarduser@example.com', EmailEncodingKey='UTF-8', 
                          LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US', ProfileId = profile.Id,
        				  TimeZoneSidKey='America/Los_Angeles', UserName = TEST_USERNAME);
        insert user;        
        Lead lead = new Lead(LastName = LEAD_NAME, Company = LEAD_NAME);
        insert lead; 
    }
    
    @isTest
    static void testInsertLeadTeam()
    {
        Lead lead = [SELECT Id FROM Lead WHERE LastName = :LEAD_NAME];
        User user = [SELECT Id FROM User WHERE Username = :TEST_USERNAME];
        Lead_Team__c leadTeam = new Lead_Team__c(Lead__c = lead.Id, Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT);
        
        Test.startTest();
        insert leadTeam;
        Test.stopTest();
        
        List<LeadShare> leadShares = [SELECT Id FROM LeadShare WHERE LeadId = :lead.Id AND UserOrGroupId = :user.Id AND RowCause = :SHARING_REASON];
        System.assertEquals(1, leadShares.size());
    }
    
    @isTest
    static void testUpdateLeadTeam()
    {
        Lead lead = [SELECT Id FROM Lead WHERE LastName = :LEAD_NAME];
        User user = [SELECT Id FROM User WHERE Username = :TEST_USERNAME];
        Lead_Team__c leadTeam = new Lead_Team__c(Lead__c = lead.Id, Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT);
        
        Test.startTest();
        insert leadTeam;        
        update leadTeam;
        Test.stopTest();
        
        List<LeadShare> leadShares = [SELECT Id FROM LeadShare WHERE LeadId = :lead.Id AND UserOrGroupId = :user.Id AND RowCause = :SHARING_REASON];
        System.assertEquals(1, leadShares.size());
    }

    @isTest
    static void testDeleteLeadTeam()
    {
        Lead lead = [SELECT Id FROM Lead WHERE LastName = :LEAD_NAME];
        User user = [SELECT Id FROM User WHERE Username = :TEST_USERNAME];
        Lead_Team__c leadTeam = new Lead_Team__c(Lead__c = lead.Id, Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT);
        
        Test.startTest();
        insert leadTeam;        
        delete leadTeam;
        Test.stopTest();
        
        List<LeadShare> leadShares = [SELECT Id FROM LeadShare WHERE LeadId = :lead.Id AND UserOrGroupId = :user.Id AND RowCause = :SHARING_REASON];
        System.assertEquals(0, leadShares.size());
    }

	@isTest
	static void testDeleteDefaultLeadTeam()
    {
        User user = [SELECT Id FROM User WHERE Username = :TEST_USERNAME];
        Default_Lead_Team__c defaultLeadTeam = new Default_Lead_Team__c(Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT, Team_Role__c = TEAM_ROLE_ACCOUNT_MANAGER);
        insert defaultLeadTeam;

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(defaultLeadTeam);
        DeleteDefaultLeadTeamController ctrl = new DeleteDefaultLeadTeamController(sc);
        ctrl.deleteRecord();
        Test.stopTest();
        
        List<Default_Lead_Team__c> defaultLeadTeams = [SELECT Id FROM Default_Lead_Team__c WHERE Id = :defaultLeadTeam.Id];
        System.assertEquals(0, defaultLeadTeams.size());        
    }
    
	@isTest
	static void testDeleteDefaultLeadTeam_WithDeleteLeadTeam()
    {
        Lead lead = [SELECT Id FROM Lead WHERE LastName = :LEAD_NAME];
        User user = [SELECT Id FROM User WHERE Username = :TEST_USERNAME];
        Default_Lead_Team__c defaultLeadTeam = new Default_Lead_Team__c(Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT, Team_Role__c = TEAM_ROLE_ACCOUNT_MANAGER);
        insert defaultLeadTeam;        
        Lead_Team__c leadTeam = new Lead_Team__c(Lead__c = lead.Id, Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT);
        insert leadTeam;

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(defaultLeadTeam);
        DeleteDefaultLeadTeamController ctrl = new DeleteDefaultLeadTeamController(sc);
        ctrl.deleteLeadTeam = true;
        ctrl.deleteRecord();
        ctrl.cancel();
        Test.stopTest();
        
        List<Default_Lead_Team__c> defaultLeadTeams = [SELECT Id FROM Default_Lead_Team__c WHERE Id = :defaultLeadTeam.Id];
        System.assertEquals(0, defaultLeadTeams.size()); 
        List<Lead_Team__c> leadTeams = [SELECT Id FROM Lead_Team__c WHERE Lead__c = :lead.Id];
        System.assertEquals(0, leadTeams.size());          
    } 
    
	@isTest
	static void testCreateDefaultLeadTeam()
    {
        Lead lead = [SELECT Id FROM Lead WHERE LastName = :LEAD_NAME];
        User user = [SELECT Id FROM User WHERE Username = :TEST_USERNAME];
        Default_Lead_Team__c defaultLeadTeam = new Default_Lead_Team__c(Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT, Team_Role__c = TEAM_ROLE_ACCOUNT_MANAGER);        		        
        
        Test.startTest();
        List<Default_Lead_Team__c> defaultLeadTeams = new List<Default_Lead_Team__c>();
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(defaultLeadTeams);
        CreateDefaultLeadTeamController ctrl = new CreateDefaultLeadTeamController(sc);    
        ctrl.defaultLeadTeams.add(defaultLeadTeam);        
        ctrl.save();        
        Test.stopTest();
        
        List<Default_Lead_Team__c> defaultLeadTeamsInDB = [SELECT Id FROM Default_Lead_Team__c WHERE OwnerId = :System.UserInfo.getUserId()];
        System.assertEquals(1, defaultLeadTeamsInDB.size());        
    }

	@isTest
	static void testCreateDefaultLeadTeam_WithUpdateLeadTeam_ExistingLeadTeam()
    {
        Lead lead = [SELECT Id FROM Lead WHERE LastName = :LEAD_NAME];
        User user = [SELECT Id FROM User WHERE Username = :TEST_USERNAME];
        Default_Lead_Team__c defaultLeadTeam = new Default_Lead_Team__c(Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT, Team_Role__c = TEAM_ROLE_ACCOUNT_MANAGER);        		          
        Lead_Team__c leadTeam = new Lead_Team__c(Lead__c = lead.Id, Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT);
        insert leadTeam;       
        
        Test.startTest();
        List<Default_Lead_Team__c> defaultLeadTeams = new List<Default_Lead_Team__c>();
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(defaultLeadTeams);
        CreateDefaultLeadTeamController ctrl = new CreateDefaultLeadTeamController(sc);    
        ctrl.defaultLeadTeams.add(defaultLeadTeam);
		ctrl.updateLeadTeam = true;        
        ctrl.saveAndMore();
		ctrl.cancel();        
        Test.stopTest();
        
        List<Lead_Team__c> leadTeamsInDB = [SELECT Id FROM Lead_Team__c WHERE Lead__c = :lead.Id];
        System.assertEquals(1, leadTeamsInDB.size());        
    }
    
	@isTest
	static void testCreateDefaultLeadTeam_WithUpdateLeadTeam_NewLeadTeam()
    {
        Lead lead = [SELECT Id FROM Lead WHERE LastName = :LEAD_NAME];
        User user = [SELECT Id FROM User WHERE Username = :TEST_USERNAME];
        Default_Lead_Team__c defaultLeadTeam = new Default_Lead_Team__c(Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT, Team_Role__c = TEAM_ROLE_ACCOUNT_MANAGER);  		                  
        
        Test.startTest();
        List<Default_Lead_Team__c> defaultLeadTeams = new List<Default_Lead_Team__c>();
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(defaultLeadTeams);
        CreateDefaultLeadTeamController ctrl = new CreateDefaultLeadTeamController(sc);    
        ctrl.defaultLeadTeams.add(defaultLeadTeam);
		ctrl.updateLeadTeam = true;        
        ctrl.saveAndMore();
		ctrl.cancel();        
        Test.stopTest();
        
        List<Lead_Team__c> leadTeamsInDB = [SELECT Id FROM Lead_Team__c WHERE Lead__c = :lead.Id];
        System.assertEquals(1, leadTeamsInDB.size());        
    }    
    
	@isTest
	static void testCreateDefaultLeadTeam_ExistingDefaultLeadTeam()
    {
        Lead lead = [SELECT Id FROM Lead WHERE LastName = :LEAD_NAME];
        User user = [SELECT Id FROM User WHERE Username = :TEST_USERNAME];
        Default_Lead_Team__c defaultLeadTeam = new Default_Lead_Team__c(Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT, Team_Role__c = TEAM_ROLE_ACCOUNT_MANAGER);
		insert defaultLeadTeam;     
        
        Test.startTest();
        List<Default_Lead_Team__c> defaultLeadTeams = new List<Default_Lead_Team__c>();
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(defaultLeadTeams);
        CreateDefaultLeadTeamController ctrl = new CreateDefaultLeadTeamController(sc);    
        defaultLeadTeam.Id = null;
        defaultLeadTeam.Team_Role__c = TEAM_ROLE_CHANNEL_MANAGER;
        ctrl.defaultLeadTeams.add(defaultLeadTeam);		        
        ctrl.save();		
        Test.stopTest();
        
        List<Default_Lead_Team__c> defaultLeadTeamsInDB = [SELECT Team_Role__c FROM Default_Lead_Team__c WHERE OwnerId = :System.UserInfo.getUserId()];
        System.assertEquals(1, defaultLeadTeamsInDB.size()); 
        System.assertEquals(TEAM_ROLE_CHANNEL_MANAGER, defaultLeadTeamsInDB.get(0).Team_Role__c); 
    }
    
	static void testCreateDefaultLeadTeam_ExistingLeadTeam()
    {
        Lead lead = [SELECT Id FROM Lead WHERE LastName = :LEAD_NAME];
        User user = [SELECT Id FROM User WHERE Username = :TEST_USERNAME];
        Default_Lead_Team__c defaultLeadTeam = new Default_Lead_Team__c(Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT, Team_Role__c = TEAM_ROLE_ACCOUNT_MANAGER);		        		          
        Lead_Team__c leadTeam = new Lead_Team__c(Lead__c = lead.Id, Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT, Team_Role__c = TEAM_ROLE_CHANNEL_MANAGER);
        insert leadTeam;       
        
        Test.startTest();
        List<Default_Lead_Team__c> defaultLeadTeams = new List<Default_Lead_Team__c>();
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(defaultLeadTeams);
        CreateDefaultLeadTeamController ctrl = new CreateDefaultLeadTeamController(sc);    
        ctrl.updateLeadTeam = true;
        defaultLeadTeam.Id = null;        
        ctrl.defaultLeadTeams.add(defaultLeadTeam);		        
        ctrl.save();		
        Test.stopTest();
        
        List<Lead_Team__c> leadTeamsInDB = [SELECT Team_Role__c FROM Lead_Team__c WHERE Lead__c = :lead.Id];
        System.assertEquals(1, leadTeamsInDB.size());  
        System.assertEquals(TEAM_ROLE_CHANNEL_MANAGER, leadTeamsInDB.get(0).Team_Role__c);
    }
    
	@isTest
	static void testEditDefaultLeadTeam()
    {
        Lead lead = [SELECT Id FROM Lead WHERE LastName = :LEAD_NAME];
        User user = [SELECT Id FROM User WHERE Username = :TEST_USERNAME];
        Default_Lead_Team__c defaultLeadTeam = new Default_Lead_Team__c(Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT, Team_Role__c = TEAM_ROLE_ACCOUNT_MANAGER);        		        
        insert defaultLeadTeam;
        
        Test.startTest();
        List<Default_Lead_Team__c> defaultLeadTeams = new List<Default_Lead_Team__c>();
        ApexPages.StandardController sc = new ApexPages.StandardController(defaultLeadTeam);
        EditDefaultLeadTeamController ctrl = new EditDefaultLeadTeamController(sc);  
        defaultLeadTeam.Team_Role__c = TEAM_ROLE_CHANNEL_MANAGER;
        ctrl.defaultLeadTeam = defaultLeadTeam;
        ctrl.save();     
        ctrl.cancel();
        Test.stopTest();
        
        List<Default_Lead_Team__c> defaultLeadTeamsInDB = [SELECT Team_Role__c FROM Default_Lead_Team__c WHERE OwnerId = :System.UserInfo.getUserId()];
        System.assertEquals(1, defaultLeadTeamsInDB.size()); 
        System.assertEquals(TEAM_ROLE_CHANNEL_MANAGER, defaultLeadTeamsInDB.get(0).Team_Role__c);
    }

    @isTest
    static void testCreateOrUpdateLeadTeam_NewLeadTeam()
    {
        Lead lead = [SELECT Id FROM Lead WHERE LastName = :LEAD_NAME];
        User user = [SELECT Id FROM User WHERE Username = :TEST_USERNAME];
        Lead_Team__c leadTeam = new Lead_Team__c(Lead__c = lead.Id, Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT);
        List<Lead_Team__c> leadTeams = new List<Lead_Team__c>();
        leadTeams.add(leadTeam);
        
        Test.startTest();
        LeadTeamController.createOrUpdateLeadTeam(leadTeams);
        Test.stopTest();
        
        List<Lead_Team__c> leadTeamsInDB = [SELECT Id FROM Lead_Team__c WHERE Lead__c = :lead.Id];
        System.assertEquals(1, leadTeamsInDB.size());
    } 
    
    @isTest
    static void testCreateOrUpdateLeadTeam_ExistingLeadTeam()
    {
        Lead lead = [SELECT Id FROM Lead WHERE LastName = :LEAD_NAME];
        User user = [SELECT Id FROM User WHERE Username = :TEST_USERNAME];
        Lead_Team__c leadTeam = new Lead_Team__c(Lead__c = lead.Id, Team_Member__c = user.Id, Lead_Access__c = TEAM_ACCESS_EDIT, Team_Role__c = TEAM_ROLE_ACCOUNT_MANAGER);
        insert leadTeam;
        List<Lead_Team__c> leadTeams = new List<Lead_Team__c>();
        leadTeams.add(leadTeam);
        
        Test.startTest();
        leadTeam.Team_Role__c = TEAM_ROLE_CHANNEL_MANAGER;
        LeadTeamController.createOrUpdateLeadTeam(leadTeams);
        Test.stopTest();
        
        List<Lead_Team__c> leadTeamsInDB = [SELECT Team_Role__c FROM Lead_Team__c WHERE Lead__c = :lead.Id];
        System.assertEquals(1, leadTeamsInDB.size());
        System.assertEquals(TEAM_ROLE_CHANNEL_MANAGER, leadTeamsInDB.get(0).Team_Role__c);
    }     
}