force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The customer account that owns and is responsible for the project</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Opportunity_Sum__c.field-meta.xml
<CustomField>
    <fullName>Total_Opportunity_Sum__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Sum of all publish to forecast opportunities related to this Project.</inlineHelpText>
    <label>Total Opportunity Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Account__c/Project_Account__c.object-meta.xml
<CustomObject>
    <label>Project Account Connection</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Account Connections</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects Involved</relationshipLabel>
    <relationshipName>Project_Account_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Account__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts Involved</relationshipLabel>
    <relationshipName>Project_Account_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectTrigger_Test.cls
@isTest
public class ProjectTrigger_Test {
    static List<Account> mAccounts;
    static Project__c mProject;
    
    static void setupTestData()
    {
        mAccounts = TestUtility.createAccountRecords(1, True);
        insert mProject = new Project__c(Name='Project Name', Account__c = mAccounts[0].id, Total_Opportunity_Sum__c = 0, CurrencyISOCode = 'AUD');
    }
    
    @isTest static void UpdateProjectCurrency()
    { 
        setupTestData();
        Test.startTest();
        Project__c QProject = [Select Id, Name, Total_Opportunity_Sum__c  from Project__c Where Name =: mProject.Name];
        update mProject = new Project__c(id = QProject.id, CurrencyISOCode = 'GBP');
        Test.stopTest();
    }
    
    @isTest
    static void testDeleteProject()
    {
        Account account = new Account(Name = 'Test', BillingCity = 'Kuala Lumpur', BillingPostalCode = '12345', BillingCountry = 'Malaysia');
        insert account;
        Project__c project = new Project__c(Name = 'PROJECT_NAME', Account__c = account.Id);
        insert project; 
        Project_Account__c mProjectAccount = new Project_Account__c(Account__c = account.Id , Project__c = project.Id);
        insert mProjectAccount;
        
        Test.startTest();
        delete project;
        Test.stopTest();
    }  

}