force-app/main/default/objects/Order_Contact_Role__c/Order_Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Order Contact Role</label>
    <nameField>
        <displayFormat>OCR-{00000000}</displayFormat>
        <label>Order Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact is Inactive.</errorMessage>
        <filterItems>
            <field>Contact.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Order Contact Roles</relationshipLabel>
    <relationshipName>Order_Contact_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Contact_Role__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Contact Roles</relationshipLabel>
    <relationshipName>Order_Contact_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Contact_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business User</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Economic Buyer</fullName>
            </value>
            <value>
                <fullName>Economic Decision Maker</fullName>
            </value>
            <value>
                <fullName>Evaluator</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
            <value>
                <fullName>Technical Buyer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderContactRolesController_Test.cls
@isTest
public class OrderContactRolesController_Test 
{
	static final String TEST_USERNAME = 'testuser@mail.weir.invalid';
    static final String ACCOUNT_NAME = 'Test';
    static final String ORDER_NAME = 'Test';
    static final String SHARING_REASON = 'Team__c';
    static final String TEAM_ACCESS_EDIT = 'Edit';
    static final String TEAM_ROLE_ACCOUNT_MANAGER = 'Account Manager';
    static final String TEAM_ROLE_CHANNEL_MANAGER = 'Channel Manager';
    
    static final String CONTACT_FIRSTNAME = 'TestFirstName';
    static final String CONTACT_LASTNAME = 'TestLastName';
    
    static Account account;
    static Contact contact;
    static Contact newContact;
    static Order ord;
    static User user;
    
    @testSetup
    static void setupData()
    {
        Profile profile = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User user = new User(Alias = 'standt', Email='standarduser@example.com', EmailEncodingKey='UTF-8', 
                          LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US', ProfileId = profile.Id,
        				  TimeZoneSidKey='America/Los_Angeles', UserName = TEST_USERNAME);
        insert user;
        account = new Account(Name = ACCOUNT_NAME, BillingCity = 'Kuala Lumpur', BillingPostalCode = '12345', BillingCountry = 'Malaysia');
        insert account;
        contact = new contact(FirstName = CONTACT_FIRSTNAME ,LastName = CONTACT_LASTNAME, AccountId  = account.Id);
        insert contact;
        ord = new Order(Name = ORDER_NAME, AccountId = account.Id, EffectiveDate = System.today(), Status = 'Draft');
        insert ord;
    }
    
    @isTest
    static void testInsertandUpdateOrderContactRoles()
    {
        Order ord = [SELECT Id FROM Order WHERE Name = :ORDER_NAME];
        Contact contact = [SELECT Id FROM Contact WHERE FirstName = :CONTACT_FIRSTNAME];
        Order_Contact_Role__c OrderContactRole = new Order_Contact_Role__c(Order__c = ord.id, Contact__c = contact.Id, Role__c = 'Business User');
        List<Order_Contact_Role__c> OrderContactRoles = new List<Order_Contact_Role__c>();
        OrderContactRoles.add(OrderContactRole);
        
        Test.startTest();
        insert OrderContactRole;
        OrderContactRolesController.createOrUpdateOrderContactRole(OrderContactRoles);
        Test.stopTest();
        
    }
    
    @isTest
    static void testFetchData()
    {
        Order ord = [SELECT Id FROM Order WHERE Name = :ORDER_NAME];
        Test.startTest();
        OrderContactRolesController.fetchData('FirstName', ord.id);
        Test.stopTest();  
    }
    
    @isTest
    static void testFetchDataBlank()
    {
        Order ord = [SELECT Id FROM Order WHERE Name = :ORDER_NAME];
        Test.startTest();
        OrderContactRolesController.fetchData('', ord.id);
        Test.stopTest();  
    }
    
    @isTest
    static void testFetchDataById()
    {
        Contact contact = [SELECT Id FROM Contact WHERE FirstName = :CONTACT_FIRSTNAME];
        Test.startTest();
        OrderContactRolesController.fetchDataById(contact.id);
        Test.stopTest();  
    }
    
    @isTest
    static void testGetPrimaryContact()
    {
        Order ord = [SELECT Id FROM Order WHERE Name = :ORDER_NAME];
        Test.startTest();
        OrderContactRolesController.getPrimaryContact(ord.id);
        OrderContactRolesController.getOrderContactRoles(ord.id);
        
        Test.stopTest();  
    }
    
}