force-app/main/default/objects/Material_Number__c/Material_Number__c.object-meta.xml
<CustomObject>
    <label>Material Number</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Number</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Number__c/fields/Material_Description__c.field-meta.xml
<CustomField>
    <fullName>Material_Description__c</fullName>
    <label>Material Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Availability_to_Promise_ATP__c.field-meta.xml
<CustomField>
    <fullName>Availability_to_Promise_ATP__c</fullName>
    <label>Availability-to-Promise (ATP)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Availability_to_Promise_ATP_Display__c.field-meta.xml
<CustomField>
    <fullName>Availability_to_Promise_ATP_Display__c</fullName>
    <formula>IF (Availability_to_Promise_ATP__c &gt; TODAY(), TEXT(Availability_to_Promise_ATP__c - TODAY()) &amp; &quot; days to go&quot;, TEXT(TODAY() - Availability_to_Promise_ATP__c) &amp; &quot; days ago&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Availability-to-Promise (ATP) Display</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Material_Description__c.field-meta.xml
<CustomField>
    <fullName>Material_Description__c</fullName>
    <formula>Material_Number__r.Material_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Material_Number__c</description>
    <label>Material Number</label>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderController.cls
public with sharing class OrderController 
{
    @AuraEnabled
    public static List<ATPTimelineWrapper> getATPTimeline(Id recordId) 
    {
        List<OrderItem> orderItems = [SELECT Availability_to_Promise_ATP__c, Availability_to_Promise_ATP_Display__c, Product2.Name, UnitPrice, Quantity,
            Material_Number__r.Name, Material_Number__r.Material_Description__c  
            FROM OrderItem 
            WHERE OrderId = :recordId
            AND Availability_to_Promise_ATP__c != NULL
            ORDER BY Availability_to_Promise_ATP__c ASC];

        Map<Date, ATPTimelineWrapper> atpTimelines = new Map<Date, ATPTimelineWrapper>();
        for (OrderItem item : orderItems)
        {
            Date atpDate = item.Availability_to_Promise_ATP__c;
            if (!atpTimelines.containsKey(atpDate))
            {
                ATPTimelineWrapper atpTimeline = new ATPTimelineWrapper();
                atpTimeline.atpDate = atpDate;
                atpTimeline.atpDateDisplay = item.Availability_to_Promise_ATP_Display__c;
                atpTimeline.products = new List<OrderItem>();
                atpTimelines.put(atpDate, atpTimeline);
            }
            atpTimelines.get(atpDate).products.add(item);
        }
        return atpTimelines.values();
    }

    public class ATPTimelineWrapper
    {
        @AuraEnabled        
        public Date atpDate { get; set; }
        @AuraEnabled        
        public String atpDateDisplay { get; set; }        
        @AuraEnabled
        public List<OrderItem> products { get; set; }
    }
}