force-app/main/default/objects/Material_Number__c/Material_Number__c.object-meta.xml
<CustomObject>
    <label>Material Number</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Number</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Number__c/fields/Material_Status__c.field-meta.xml
<CustomField>
    <fullName>Material_Status__c</fullName>
    <label>Material Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Number</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Material is obsolete</errorMessage>
        <filterItems>
            <field>Material_Number__c.Material_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/MaterialHierarchy__c.field-meta.xml
<CustomField>
    <fullName>MaterialHierarchy__c</fullName>
    <formula>Text(Material_Number__r.X3rd_Level_Product_Hierarchy__c)</formula>
    <label>MaterialHierarchy</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <formula>Text(PricebookEntry.Product2.Third_Level_Product_Hierarchy__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ProductHierarchy</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Update_Product_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Update_Product_Hierarchy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update Product Hierarchy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_Material__c/Sales_Organization_Material__c.object-meta.xml
<CustomObject>
    <label>Sales Organization Material</label>
    <nameField>
        <label>Sales Organization Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organization Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <formula>OR( 
 ISPICKVAL(DChain__c, &quot;03&quot;), 
 ISPICKVAL(DChain__c, &quot;14&quot;), 
 ISPICKVAL(DChain__c, &quot;25&quot;),
 ISPICKVAL(DChain__c, &quot;27&quot;), 
 ISPICKVAL(DChain__c, &quot;99&quot;), 
 ISPICKVAL(DChain__c, &quot;G2&quot;), 
 ISPICKVAL(DChain__c, &quot;G3&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Block</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <formula>Sales_Organization__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Deletion__c.field-meta.xml
<CustomField>
    <fullName>Deletion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <label>Material Number</label>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Sales Organization Materials</relationshipLabel>
    <relationshipName>Sales_Organization_Materials</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_User__c/Sales_Organization_User__c.object-meta.xml
<CustomObject>
    <label>Sales Organization User</label>
    <nameField>
        <label>Sales Organization User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organization Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Organization_User__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <formula>Sales_Organizationa__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityLineItemTriggerHandler.cls
public class OpportunityLineItemTriggerHandler {
    
    public static Set<Id> oppIds = new Set <Id>();
    public static Set<Id> MaterialIds = new Set<Id>();    
    public static String saleOrgCode ;
    public static List<String> saleOrgCodes = new List<String>();
    public static List<String> invalidHierarchyList = new List<String>();
    public static Map<String,Id> pbEntryMap = new Map<String,Id>();
    public static Map<String,String> invalidHierarchyMap = new Map<String,String>();
    public static Map<Id,String> oppSaleOrgMap = new Map<Id,String>();
    public static Map<Id, List<OpportunityLineItem >> oppItemsMap = new Map<Id, List<OpportunityLineItem >>();
    public static Map<String, List<Sales_Organization_Material__c >> saleOrgMaterialMap = new Map<String, List<Sales_Organization_Material__c >>();
    public static Map<String,Sales_Organization_Material__c> saleOrgMaterialChannelMap = new Map<String,Sales_Organization_Material__c>();
    
    public static void ValidateSalesOrgMaterialmethod(List<OpportunityLineItem> mNewOppLineItem, String TriggerEvent)
    {
        Id profileId = userinfo.getProfileId();
        String profileName = [Select Id,Name from Profile where Id=:profileId].Name;
        system.debug('ProfileName: '+profileName);
        
        System.debug('opportunityItem Size: '+mNewOppLineItem.size());            
        for(OpportunityLineItem oli : mNewOppLineItem)
        {
            if (oli.Material_Number__c != null)
            {
                MaterialIds.add(oli.Material_Number__c);
                if(oli.ProductHierarchy__c != oli.MaterialHierarchy__c && oli.MaterialHierarchy__c != null)
                    invalidHierarchyList.add(oli.MaterialHierarchy__c);
            }
            
            if(!oppItemsMap.containsKey(oli.OpportunityId)){
                oppItemsMap.put(oli.OpportunityId, new List<OpportunityLineItem >{oli});
            }
            else{
                oppItemsMap.get(oli.OpportunityId).add(oli);
            }
        }

        System.debug(invalidHierarchyList.size()+'  invalidHierarchyList: '+invalidHierarchyList);
        
        List<Opportunity> opportunities = [SELECT Id, Name, Sales_Organization_User__c ,Sales_Organization_User__r.code__c, 
                                           OwnerId, Recordtype.Name, CurrencyIsoCode, Channel__c, Number_of_Quotations__c, Lock_Opportunity__c
                                           FROM Opportunity WHERE Id IN :oppItemsMap.keySet()];
        
        for (Opportunity opportunity : opportunities)
        {
            if(opportunity.Sales_Organization_User__c != null)
            {
                saleOrgCodes.add(opportunity.Sales_Organization_User__r.code__c);
            }
        }
        
        List<Sales_Organization_Material__c> saleOrgMaterials = [SELECT Id, Code__c, Material_Number__c, Material_Number__r.Name, Material_Number__r.Material_Status__c,
                                                                 Block__c, Deletion__c, Distribution_Channel__c 
                                                                 FROM Sales_Organization_Material__c
                                                                 WHERE Code__c IN: saleOrgCodes AND Material_Number__c IN :MaterialIds AND Distribution_Channel__c != null];
        for (Sales_Organization_Material__c som : saleOrgMaterials)
        {            
            if(!saleOrgMaterialMap.containsKey(som.Code__c + som.Material_Number__c)){
                saleOrgMaterialMap.put(som.Code__c + som.Material_Number__c, new List<Sales_Organization_Material__c >{som});
            }
            else{
                saleOrgMaterialMap.get(som.Code__c + som.Material_Number__c).add(som);
            }
           
            if(!saleOrgMaterialChannelMap.containsKey(som.Code__c + som.Material_Number__c + som.Distribution_Channel__c)){
                saleOrgMaterialChannelMap.put(som.Code__c + som.Material_Number__c + som.Distribution_Channel__c, som);
            }
        }
        
        
        for (Opportunity opportunity : opportunities) 
        {
            Boolean validated = true;
            if(opportunity.Recordtype.Name.contains('SGT'))
            {
                if(opportunity.Number_of_Quotations__c > 0 && opportunity.Lock_Opportunity__c == true  && profileName != 'Integration') //&& profileName != 'System Administrator'
                {
                    /*for(OpportunityLineItem oli2 : mNewOppLineItem)
                    {
                        oli2.addError('A Quote has been created, Cannot update opportunity items');
                        validated = false;
                        break;
                    }*/
                }
                else
                {
                    if(opportunity.Sales_Organization_User__c != null)
                    {
                        String saleOrgCode = opportunity.Sales_Organization_User__r.code__c;
                        System.debug('Trigger OpportunityLineItemTriggerHandler');
                        System.debug('saleOrgCode: '+saleOrgCode);
                        if(!MaterialIds.isEmpty())
                        {   
                            system.debug(opportunity.Id+' has Items size '+oppItemsMap.get(opportunity.Id).size());
                            for(OpportunityLineItem oli1 : oppItemsMap.get(opportunity.Id))
                            {
                                //system.debug('oli ------------ '+oli1);
                                if(profileName != 'System Administrator' && profileName != 'Integration')
                                {
                                    // Check Sale Org Material
                                    if(!saleOrgMaterialMap.isEmpty() && saleOrgMaterialMap.containsKey(saleOrgCode + oli1.Material_Number__c))
                                    { 
                                        system.debug('saleOrgMateria size '+saleOrgMaterialMap.get(saleOrgCode + oli1.Material_Number__c).size());
                                        
                                        if(saleOrgMaterialChannelMap.containsKey(saleOrgCode + oli1.Material_Number__c + opportunity.Channel__c))
                                        {
                                            Sales_Organization_Material__c saleOrgMat = saleOrgMaterialChannelMap.get(saleOrgCode + oli1.Material_Number__c + opportunity.Channel__c);
                                            system.debug('saleOrgMat '+saleOrgMat);
                                            if(saleOrgMat.Block__c == true || saleOrgMat.Deletion__c == true)
                                            {
                                                oli1.addError('Material '+saleOrgMat.Material_Number__r.Name+' is blocked for '+saleOrgCode+ '/'+opportunity.Channel__c);
                                                System.debug('Material '+saleOrgMat.Material_Number__r.Name+' is blocked for '+saleOrgCode+ '/'+opportunity.Channel__c);
                                                validated = false;
                                                break;
                                            }
                                        }
                                        else
                                        {
                                            oli1.addError('This Material Number is not extended to Sales Org: '+ saleOrgCode+', Dis Channel: '+opportunity.Channel__c+' usage');
                                            System.debug('This Material Number is not extended to Sales Org: '+ saleOrgCode+', Dis Channel: '+opportunity.Channel__c+' usage');
                                            validated = false;
                                            break;
                                        }
                                    }
                                    else
                                    {
                                        oli1.addError('This material is not extended to Sales Org '+saleOrgCode+ ' usage');
                                        System.debug('This material is not extended to Sales Org '+saleOrgCode+ ' usage');
                                        validated = false;
                                        break;
                                    }
                                }
                            }
                        }
                    }
                    else
                    {
                        for(OpportunityLineItem oli2 : mNewOppLineItem)
                        {
                            oli2.addError('Please enter User Sales Organization in Opportunity');
                            validated = false;
                            break;
                        }
                    } 
                }
            }
            else
            {
                System.debug('No SalesOrg Product Validation and Populate ProductHierarchy for Standalone Record Type');
                validated = false;
            }
            
            //--------------------Validate Product Hierarchy-------------------------------------------//
            
            if(TriggerEvent == 'IsInsert' && validated == true)
            {
                if(!invalidHierarchyList.isEmpty())
                {
                    PopulateProductHierarchy(mNewOppLineItem,invalidHierarchyList,Opportunity);
                }
            }
        }      
        
    }
    
    public static void PopulateProductHierarchy(List<OpportunityLineItem> mNewOppLineItem, List<String> invalidHierarchyList, Opportunity mOpportunity)
    {
        System.debug(invalidHierarchyList.size()+'  invalidHierarchyList: '+invalidHierarchyList);
        for(PricebookEntry pbEntry : [SELECT Id, Name, Pricebook2Id, CurrencyIsoCode, Product2.Third_Level_Product_Hierarchy__c
                                      FROM PricebookEntry WHERE IsActive = true AND CurrencyIsoCode =: mOpportunity.CurrencyIsoCode
                                      AND Product2.Third_Level_Product_Hierarchy__c IN: invalidHierarchyList])
        {
            pbEntryMap.put(pbEntry.Product2.Third_Level_Product_Hierarchy__c, pbEntry.id);
            System.debug('pbEntryMap Size : '+pbEntryMap.size()+' pbEntryMap: ' + pbEntryMap);
            for(OpportunityLineItem oli : mNewOppLineItem)
            {
                for(String hierarchy : invalidHierarchyList)
                {
                    if(oli.MaterialHierarchy__c == hierarchy)
                    {
                        //system.debug('Update hierarchy : '+hierarchy);
                        oli.PricebookEntryId = pbEntryMap.get(hierarchy);
                        oli.Update_Product_Hierarchy__c = true;
                    }
                }
            }
        }
    } 
}