force-app/main/default/objects/Material_Number__c/Material_Number__c.object-meta.xml
<CustomObject>
    <label>Material Number</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Number</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem/fields/Availability_to_Promise_ATP__c.field-meta.xml
<CustomField>
    <fullName>Availability_to_Promise_ATP__c</fullName>
    <label>Availability-to-Promise (ATP)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Material_Number__c</description>
    <label>Material Number</label>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderTest.cls
@isTest
public class OrderTest 
{
    @TestSetup
    static void setupData()
    {
        Id STDPriceBookId = TestUtility.createSTDPriceBookRecords();
        List<Product2> products = TestUtility.createProductRecords(1, 'Z0001S0001', True);
        List<PricebookEntry> pbes = TestUtility.createPricebookEntryRecords(1, products[0].Id, STDPriceBookId,'AUD', True);
        List<Material_Number__c> materials = TestUtility.createMaterialRecords(1, 'Mat123', True);
        List<Account> accounts = TestUtility.createAccountRecords(1, TRUE);
        Order ord = new Order();
        ord.Pricebook2Id = STDPriceBookId;
        ord.CurrencyIsoCode = 'AUD';
        ord.AccountId = accounts.get(0).Id;
        ord.Status = 'Draft';
        ord.EffectiveDate = System.today();      
        insert ord;      
    }

    @isTest
    static void testGetATPTimeline_NoProducts() {

        Id ordId = [SELECT Id FROM Order].Id;
        Test.startTest();
        List<OrderController.ATPTimelineWrapper> results = OrderController.getATPTimeline(ordId);
        Test.stopTest();

        System.assertEquals(0, results.size(), 'No results as no order lines were created.');
    }    

    @isTest
    static void testGetATPTimeline_WithProducts() {
        
        Id ordId = [SELECT Id FROM Order].Id;      
        OrderItem oi = new OrderItem();
        oi.PricebookEntryId = [SELECT Id FROM PricebookEntry].Id;
        oi.Quantity = 1;  
        oi.OrderId = ordId;
        oi.UnitPrice = 1;
        oi.Availability_to_Promise_ATP__c = System.today();
        oi.Material_Number__c = [SELECT Id FROM Material_Number__c].Id;
        insert oi;  

        Test.startTest();
        List<OrderController.ATPTimelineWrapper> results = OrderController.getATPTimeline(ordId);
        Test.stopTest();

        System.assertEquals(1, results.size(), 'One Order Line has to be returned.');

    }     
    
}