force-app/main/default/objects/Default_Order_Team__c/Default_Order_Team__c.object-meta.xml
<CustomObject>
    <label>Default Order Team</label>
    <nameField>
        <displayFormat>DLTN-{00000000}</displayFormat>
        <label>Default Order Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Order Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_Order_Team__c/fields/Order_Access__c.field-meta.xml
<CustomField>
    <fullName>Order_Access__c</fullName>
    <label>Order Access</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Order_Access</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Default_Order_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Default_Order_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Default_Order_Team__c/fields/Team_Role__c.field-meta.xml
<CustomField>
    <fullName>Team_Role__c</fullName>
    <label>Team Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Order_Team_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Setting__c/User_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>User related settings - Enable defaulting of Project Team on Projects/Order Team on Orders.</description>
    <label>User - Setting</label>
</CustomObject>

force-app/main/default/globalValueSets/Order_Access.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Edit</fullName>
        <default>true</default>
        <label>Read/Write</label>
    </customValue>
    <customValue>
        <fullName>Read</fullName>
        <label>Read Only</label>
    </customValue>
    <masterLabel>Order Access</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Order_Team_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Executive Sponsor</fullName>
    </customValue>
    <customValue>
        <fullName>Order Qualifier</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Sales Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Rep</fullName>
    </customValue>
    <masterLabel>Order Team Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EditDefaultOrderTeamController.cls
public class EditDefaultOrderTeamController
{
    public User user { get; set; }
    public User_Setting__c userSetting { get; set; }
    public Boolean updateOrderTeam { get; set; }
    public Default_Order_Team__c defaultOrderTeam { get; set; }
    
    public EditDefaultOrderTeamController(ApexPages.StandardController stdController)
    {
        defaultOrderTeam = (Default_Order_Team__c) stdController.getRecord();
        init();
    }
    
    public void init()
    {        
        defaultOrderTeam = [SELECT OwnerId, Order_Access__c, Team_Role__c, Team_Member__c, Team_Member__r.Name FROM Default_Order_Team__c WHERE Id = :defaultOrderTeam.Id];
        user = [SELECT Name FROM User WHERE Id = :defaultOrderTeam.OwnerId];
        userSetting = User_Setting__c.getInstance(user.Id);
        updateOrderTeam = false;
    }

    public PageReference save()
    {        
        List<Default_Order_Team__c> defaultOrderTeams = new List<Default_Order_Team__c>();
        defaultOrderTeams.add(defaultOrderTeam);
        boolean success = OrderTeamController.createOrUpdateDefaultOrderTeam(defaultOrderTeams, user.Id, updateOrderTeam);
        if (success)
        {
        	upsert userSetting;   
        }
        return new PageReference('/' + userSetting.SetupOwnerId);
    }  
    
    public PageReference cancel()
    {		       
        return new PageReference('/' + userSetting.SetupOwnerId);
    }
}