force-app/main/default/objects/Default_Order_Team__c/Default_Order_Team__c.object-meta.xml
<CustomObject>
    <label>Default Order Team</label>
    <nameField>
        <displayFormat>DLTN-{00000000}</displayFormat>
        <label>Default Order Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Order Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Setting__c/User_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>User related settings - Enable defaulting of Project Team on Projects/Order Team on Orders.</description>
    <label>User - Setting</label>
</CustomObject>

force-app/main/default/objects/User_Setting__c/fields/Enable_Default_Order_Team__c.field-meta.xml
<CustomField>
    <fullName>Enable_Default_Order_Team__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Default Order Team</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CreateDefaultOrderTeamController.cls
public class CreateDefaultOrderTeamController 
{
    public User user { get; set; }    
    public Boolean enableDefaultOrderTeam { get; set; }
    public Boolean updateOrderTeam { get; set; }
    public List<Default_Order_Team__c> defaultOrderTeams { get; set; }
    
    
    public CreateDefaultOrderTeamController(ApexPages.StandardSetController stdController)
    {
        init();
    }
    
    public void init()
    {
        Id userId = ApexPages.currentPage().getParameters().get('Id');
        if (userId == NULL)
        {
            userId = System.UserInfo.getUserId();
        }
        user = [SELECT Name FROM User WHERE Id =:userId];
        User_Setting__c userSetting = User_Setting__c.getInstance(user.Id);
        enableDefaultOrderTeam = userSetting.Enable_Default_Order_Team__c;
        updateOrderTeam = false;
        defaultOrderTeams = new List<Default_Order_Team__c>();
        for (Integer i=0; i<5; i++)
        {
            Default_Order_Team__c defaultOrderTeam = new Default_Order_Team__c(OwnerId = userId);
            defaultOrderTeams.add(defaultOrderTeam);
        }
    }
    
    public PageReference save()
    {
        boolean success = OrderTeamController.createOrUpdateDefaultOrderTeam(defaultOrderTeams, user.Id, updateOrderTeam);
        if (success)
        {
			User_Setting__c userSetting = User_Setting__c.getInstance(user.Id);
            userSetting.Enable_Default_Order_Team__c = enableDefaultOrderTeam;
			upsert userSetting;   
            
            Id userId = ApexPages.currentPage().getParameters().get('Id');
            if (userId == null)
                return new PageReference('/' + Default_Order_Team__c.sObjectType.getDescribe().getKeyPrefix());
            else
                return new PageReference('/' + user.Id);            
        }
        else return null;
    }

    public void saveAndMore()
    {        
        boolean success = OrderTeamController.createOrUpdateDefaultOrderTeam(defaultOrderTeams, user.Id, updateOrderTeam);
        if (success)
        {
			User_Setting__c userSetting = User_Setting__c.getInstance(user.Id);
            userSetting.Enable_Default_Order_Team__c = enableDefaultOrderTeam;
			upsert userSetting;        
        }
        init();
    }  
    
    public PageReference cancel()
    {		       
        Id userId = ApexPages.currentPage().getParameters().get('Id');
        if (userId == null)
        	return new PageReference('/' + Default_Order_Team__c.sObjectType.getDescribe().getKeyPrefix());
        else
        	return new PageReference('/' + user.Id);
    }    
}