force-app/main/default/objects/Default_Order_Team__c/Default_Order_Team__c.object-meta.xml
<CustomObject>
    <label>Default Order Team</label>
    <nameField>
        <displayFormat>DLTN-{00000000}</displayFormat>
        <label>Default Order Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Order Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Default_Order_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Default_Order_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Team__c/Order_Team__c.object-meta.xml
<CustomObject>
    <label>Order Team</label>
    <nameField>
        <displayFormat>LET-{0000}</displayFormat>
        <label>Order Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Teams</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Order_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeleteDefaultOrderTeamController.cls
public class DeleteDefaultOrderTeamController 
{
    public User user { get; set; }    
    public Boolean deleteOrderTeam { get; set; }
    public Default_Order_Team__c defaultOrderTeam { get; set; }
    
    public DeleteDefaultOrderTeamController(ApexPages.StandardController stdController)
    {
        defaultOrderTeam = (Default_Order_Team__c) stdController.getRecord();
        init();
    }
    
    public void init()
    {                
        defaultOrderTeam = [SELECT OwnerId, Team_Member__c FROM Default_Order_Team__c WHERE Id =:defaultOrderTeam.Id];
        user = [SELECT Name FROM User WHERE Id = :defaultOrderTeam.OwnerId];        
        deleteOrderTeam = false;
    }

    public PageReference deleteRecord()
    {        
        if (deleteOrderTeam == true)
        {
            List<Order> ownedOrders = [SELECT Id, (SELECT Team_Member__c FROM Order_Teams__r WHERE Team_Member__c = :defaultOrderTeam.Team_Member__c) FROM Order WHERE OwnerId =: user.Id];            
            List<Order_Team__c> existingOrderTeams = new List<Order_Team__c>();            
            for (Order ownedOrder : ownedOrders)
            {      
                for (Order_Team__c existingOrderTeam : ownedOrder.Order_Teams__r)
                {                                           
                    existingOrderTeams.add(existingOrderTeam);                        
                }
            } 
            delete existingOrderTeams;
        }
        delete defaultOrderTeam;        
        return new PageReference('/' + user.Id);
    }  
    
    public PageReference cancel()
    {		       
        return new PageReference('/' + user.Id);
    }
}