force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Address</relationshipLabel>
    <relationshipName>Shipping_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_ID__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Address__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <label>State Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Material_Number__c/Material_Number__c.object-meta.xml
<CustomObject>
    <label>Material Number</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Number</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Number__c/fields/ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_ID__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Number</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Material is obsolete</errorMessage>
        <filterItems>
            <field>Material_Number__c.Material_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Material_Number__c</description>
    <label>Material Number</label>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/Organization_Structure__c.object-meta.xml
<CustomObject>
    <label>Organization Structure</label>
    <nameField>
        <displayFormat>TRTY-{00000}</displayFormat>
        <label>Organization Structure Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Structure__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/Sales_District__c.field-meta.xml
<CustomField>
    <fullName>Sales_District__c</fullName>
    <label>Sales District</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/Sales_Group__c.field-meta.xml
<CustomField>
    <fullName>Sales_Group__c</fullName>
    <label>Sales Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <label>Sales Office</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/SGT__c.field-meta.xml
<CustomField>
    <fullName>SGT__c</fullName>
    <defaultValue>true</defaultValue>
    <label>SGT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/Territoty_ID__c.field-meta.xml
<CustomField>
    <fullName>Territoty_ID__c</fullName>
    <label>Territoty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Area_Detail__c/Sales_Area_Detail__c.object-meta.xml
<CustomObject>
    <label>Sales Area Detail</label>
    <nameField>
        <label>Organization Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Area_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Area Details</relationshipLabel>
    <relationshipName>Sales_Area_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Area_Detail__c/fields/Organization_Structure__c.field-meta.xml
<CustomField>
    <fullName>Organization_Structure__c</fullName>
    <label>Organization Structure</label>
    <referenceTo>Organization_Structure__c</referenceTo>
    <relationshipLabel>Sales Area Details</relationshipLabel>
    <relationshipName>Sales_Area_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Organization__c/Sales_Organization__c.object-meta.xml
<CustomObject>
    <label>Sales Organization</label>
    <nameField>
        <label>Sales Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Organization__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_Material__c/Sales_Organization_Material__c.object-meta.xml
<CustomObject>
    <label>Sales Organization Material</label>
    <nameField>
        <label>Sales Organization Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organization Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <formula>Sales_Organization__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Deletion__c.field-meta.xml
<CustomField>
    <fullName>Deletion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <label>Material Number</label>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Sales Organization Materials</relationshipLabel>
    <relationshipName>Sales_Organization_Materials</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <referenceTo>Sales_Organization__c</referenceTo>
    <relationshipLabel>Sales Organization Materials</relationshipLabel>
    <relationshipName>Sales_Organization_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_User__c/Sales_Organization_User__c.object-meta.xml
<CustomObject>
    <label>Sales Organization User</label>
    <nameField>
        <label>Sales Organization User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organization Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Organization_User__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <formula>Sales_Organizationa__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_User__c/fields/Sales_Organizationa__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organizationa__c</fullName>
    <label>Sales Organization</label>
    <referenceTo>Sales_Organization__c</referenceTo>
    <relationshipLabel>Sales Organization Users (Sales Organizationa)</relationshipLabel>
    <relationshipName>Sales_Organization_Users1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Organization_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestUtility.cls
@isTest
public class TestUtility {
    private static Id AccountSGTRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('SGT_Record_Type').getRecordTypeId ();
    private static Id OpportunitySGTRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGT_Record_Type').getRecordTypeId ();
    private static Id OpportunityStandaloneRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Standalone_Record_Type').getRecordTypeId ();
    
    public static List<Account> createAccountRecords(Integer mNum, Boolean isInsert)
    {
        List<Account> mNewAccountList = new List<Account>();
        
        for(Integer i=0; i < mNum; i++)
        {
            Account mNewAccount = new Account();
            mNewAccount.Name = 'Test Account 00' + i;
            mNewAccount.ERP_Id__c = 'Acc123'+i;
            mNewAccount.Prospect__c = True;
            mNewAccount.BillingStreet = 'Street';
            mNewAccount.BillingCity = 'KL';
            mNewAccount.BillingStateCode = 'QLD';
            mNewAccount.BillingPostalCode = '12334'; 
            mNewAccount.BillingCountryCode = 'AU';
            mNewAccount.Non_Trading__c = false;
            mNewAccount.RecordTypeId = AccountSGTRecordTypeId;
            mNewAccountList.add(mNewAccount);
        }
        
        if(isInsert == True)
        {
            insert mNewAccountList;
        }
        
        return mNewAccountList;
    }
    
    public static List<Account> createAccountRecords1(Integer mNum, String AccountERPID,Boolean isProspect,Boolean isInsert)
    {
        List<Account> mNewAccountList = new List<Account>();
        
        for(Integer i=0; i < mNum; i++)
        {
            Account mNewAccount = new Account();
            mNewAccount.Name = 'Test 12' + i;
            mNewAccount.ERP_Id__c = AccountERPID;
            mNewAccount.Prospect__c = isProspect;
            mNewAccount.Industry = 'Energy';
            mNewAccount.Industry_Code__c = 'IRON ORES';
            mNewAccount.Type = 'End User';
            mNewAccount.Phone = '00012234044';
            mNewAccount.Website = 'Account@Test.com';
            mNewAccount.CurrencyIsoCode = 'AUD';
            mNewAccount.BillingStreet = 'Street';
            mNewAccount.BillingCity = 'KL';
            mNewAccount.BillingStateCode = 'QLD';
            mNewAccount.BillingPostalCode = '14'; 
            mNewAccount.BillingCountryCode = 'AU';
            mNewAccount.Non_Trading__c = false;
            mNewAccount.RecordTypeId = AccountSGTRecordTypeId;
            mNewAccountList.add(mNewAccount);
        }
        
        if(isInsert == True)
        {
            insert mNewAccountList;
        }
        
        return mNewAccountList;
    }
    
    public static List<Address__c> createShippingRecords(Integer mNum, Id AccountId,Boolean isInsert)
    {
        List<Address__c> mShippingList = new List<Address__c>();
        
        for(Integer i=0; i < mNum; i++)
        {
            Address__c mNewShipping = new Address__c();
            mNewShipping.Account__c = AccountId;
            mNewShipping.Street__c = 'Street';
            mNewShipping.City__c = 'KL';
            mNewShipping.State_Code__c = 'QLD';
            mNewShipping.PostalCode__c = '10269';
            mNewShipping.Country_Code__c = 'AU';
            mNewShipping.ERP_ID__c = 'ship123'+1;
            mShippingList.add(mNewShipping);
        }
        
        if(isInsert == True)
        {
            insert mShippingList;
        }
        
        return mShippingList;
    }
    
    public static List<Sales_Organization__c> createSalesOrgRecords(Integer mNum, String SalesOrgCode, Boolean isInsert)
    {
        List<Sales_Organization__c> mSalesOrgList = new List<Sales_Organization__c>();
        
        for(Integer i=0; i < mNum; i++)
        {
            Sales_Organization__c mNewSalesOrg = new Sales_Organization__c();
            mNewSalesOrg.Name = 'WM SalesOrg Name';
            mNewSalesOrg.Code__c = SalesOrgCode;
            mSalesOrgList.add(mNewSalesOrg);
        }
        
        if(isInsert == True)
        {
            insert mSalesOrgList;
        }
        
        return mSalesOrgList;
    }
    
    public static List<Sales_Organization_User__c> createSalesOrgUserRecords(Integer mNum, Id UserId, Id SalesOrgId, Boolean isInsert)
    {
        List<Sales_Organization_User__c> mSalesOrgUserList = new List<Sales_Organization_User__c>();
        
        for(Integer i=0; i < mNum; i++)
        {
            Sales_Organization_User__c mNewSalesOrgUser = new Sales_Organization_User__c();
            mNewSalesOrgUser.User__c = UserId;
            mNewSalesOrgUser.Sales_Organizationa__c = SalesOrgId;
            mSalesOrgUserList.add(mNewSalesOrgUser);
        }
        
        if(isInsert == True)
        {
            insert mSalesOrgUserList;
        }
        
        return mSalesOrgUserList;
    }
    
    public static List<Opportunity> createOpportunityRecords(Integer mNum, Id AccountId, Id ShipToId, Id SaleOrgUserId, Id pricebookID, String IsoCurrency,String Channel, String Division, Boolean SGT, Boolean isInsert)
    {
        List<Opportunity> mOpportunityList = new List<Opportunity>();
        
        for(Integer i=0; i < mNum; i++)
        {
            Opportunity mNewOpportunity = new Opportunity();
            mNewOpportunity.Name = 'Test Opportunity '+i;
            mNewOpportunity.StageName = 'Qualification';
            mNewOpportunity.AccountId = AccountId;
            mNewOpportunity.Sales_Organization_User__c = SaleOrgUserId;
            mNewOpportunity.Integration_Status__c = 'Not Applicable';
            mNewOpportunity.Shipping_Address__c = ShipToId;
            mNewOpportunity.CloseDate = System.today();
            mNewOpportunity.Expected_Delivery_Date__c = System.today();
            mNewOpportunity.CurrencyIsoCode = IsoCurrency;
            mNewOpportunity.Pricebook2Id = pricebookID;
            If(SGT == True) mNewOpportunity.RecordTypeId = OpportunitySGTRecordTypeId;
            else mNewOpportunity.RecordTypeId = OpportunityStandaloneRecordTypeId;
            mNewOpportunity.Division__c = Division;
            mNewOpportunity.Channel__c =  Channel;
            mOpportunityList.add(mNewOpportunity);
        }
        
        if(isInsert == True)
        {
            insert mOpportunityList;
        }
        
        return mOpportunityList;
    }
    
    public static List<Quote> createQuoteRecords(Integer mNum, Id opportunityId, Id pricebookId, Id ShippingAddress, String quoteERPID, Boolean isInsert)
    {
        List<Quote> mNewQuoteList = new List<Quote>();
        for(Integer i=0; i < mNum; i++)
        {
            Quote mNewQuote = new Quote();
            mNewQuote.Name = 'EEC Quote - '+quoteERPID;
            mNewQuote.Status = 'Active';
            mNewQuote.Pricebook2Id = pricebookId;
            mNewQuote.OpportunityId = opportunityId;
            mNewQuote.ERP_Id__c = quoteERPID;
            mNewQuoteList.add(mNewQuote);
        }
        
        if(isInsert == True)
        {
            insert mNewQuoteList;
        }
        
        return mNewQuoteList;
    }
    
    
    public static List<Product2> createProductRecords(Integer mNum, String thirdLevelHierarchy, Boolean isInsert)
    {
        List<Product2> mNewProductList = new List<Product2>();
        
        for(Integer i=0; i < mNum; i++)
        {
            Product2 mNewProduct = new Product2();
            mNewProduct.Name = 'test product 00' + i;
            mNewProduct.IsActive = True;
            mNewProduct.Third_Level_Product_Hierarchy__c = thirdLevelHierarchy;
            mNewProductList.add(mNewProduct);
        }
        
        if(isInsert == True)
        {
            insert mNewProductList;
        }
        
        return mNewProductList;
    }
    
    public static List<Material_Number__c> createMaterialRecords(Integer mNum, String MaterialERPID, Boolean isInsert)
    {
        List<Material_Number__c> mNewMaterialList = new List<Material_Number__c>();
        
        for(Integer i=0; i < mNum; i++)
        {
            Material_Number__c mNewMaterial = new Material_Number__c();
            mNewMaterial.Name = MaterialERPID + i;
            mNewMaterial.ERP_Id__c = MaterialERPID + i;
            mNewMaterialList.add(mNewMaterial);
        }
        
        if(isInsert == True)
        {
            insert mNewMaterialList;
        }
        
        return mNewMaterialList;
    }
    
    public static List<Sales_Organization_Material__c> createSalesOrgMaterialRecords(Integer mNum, Id MaterialId, Id SalesOrgId, Boolean Deletion, Boolean isInsert)
    {
        List<Sales_Organization_Material__c> mSalesOrgMaterialList = new List<Sales_Organization_Material__c>();
        
        for(Integer i=0; i < mNum; i++)
        {
            Sales_Organization_Material__c mNewSalesOrgMaterial = new Sales_Organization_Material__c();
            mNewSalesOrgMaterial.Material_Number__c = MaterialId;
            mNewSalesOrgMaterial.Sales_Organization__c = SalesOrgId;
            mNewSalesOrgMaterial.Deletion__c = Deletion;
            mSalesOrgMaterialList.add(mNewSalesOrgMaterial);
        }
        
        if(isInsert == True)
        {
            insert mSalesOrgMaterialList;
        }
        
        return mSalesOrgMaterialList;
    }

    public static Id createSTDPriceBookRecords()
    {   
        Id pricebookId = Test.getStandardPricebookId();
        return pricebookId;
    }
    
    public static List<PricebookEntry> createPricebookEntryRecords(Integer mNum, Id productID, Id pricebookId, String IsoCurrency, Boolean isInsert)
    {
        List<PricebookEntry> mNewPricebookEntryList = new List<PricebookEntry>();
        
        for(Integer i=0; i < mNum; i++)
        {
            PricebookEntry mNewPBETItem = new PricebookEntry();
            mNewPBETItem.Product2Id = productID;
            mNewPBETItem.Pricebook2Id = pricebookId;
            mNewPBETItem.UnitPrice = 123;
            mNewPBETItem.isActive = true;
            mNewPBETItem.CurrencyIsoCode = IsoCurrency;
            mNewPricebookEntryList.add(mNewPBETItem);
        }
        
        if(isInsert == True)
        {
            insert mNewPricebookEntryList;
        }
        
        return mNewPricebookEntryList;
    }
    
    public static List<OpportunityLineItem> createOpportunityItemRecords(Integer mNum,Id opportunityId,Id productId, Id pricebookEntryID , Id MaterialId, Boolean isInsert)
    {
        List<OpportunityLineItem> mNewOppItemList = new List<OpportunityLineItem>();
        
        for(Integer i=0; i < mNum; i++)
        {
            OpportunityLineItem mNewOppItem = new OpportunityLineItem();
            mNewOppItem.OpportunityId = opportunityId;
            mNewOppItem.PricebookEntryId = pricebookEntryID;
            mNewOppItem.Product2Id = productId;
            mNewOppItem.Material_Number__c = MaterialId;
            mNewOppItem.Quantity = 2;
            mNewOppItem.UnitPrice = 10;
            mNewOppItemList.add(mNewOppItem);
        }
        
        if(isInsert == True)
        {
            insert mNewOppItemList;
        }
        
        return mNewOppItemList;
    } 
    
    public static List<QuoteLineItem> createQuoteLineItemRecords(Integer mNum,Id quoteId,Id productId, Id pricebookEntryID , Boolean isInsert)
    {
        List<QuoteLineItem> mNewQuoteLineItemList = new List<QuoteLineItem>();
        
        for(Integer i=0; i < mNum; i++)
        {
            QuoteLineItem mNewQuoteLineItem = new QuoteLineItem();
            
            mNewQuoteLineItem.QuoteId = quoteId;
            mNewQuoteLineItem.PricebookEntryId = pricebookEntryID;
            mNewQuoteLineItem.Product2Id = productId;
            mNewQuoteLineItem.Quantity = 2;
            mNewQuoteLineItem.UnitPrice = 10;
            mNewQuoteLineItemList.add(mNewQuoteLineItem);
            
        }
        
        if(isInsert == True)
        {
            insert mNewQuoteLineItemList;
        }
        
        return mNewQuoteLineItemList;
    }        
    
    public static List<QuoteCreationWebService.QuoteItems> createQuoteItemsCreate(Integer mNum,String MaterialNumber,Integer Quantity, Integer UnitPrice, String thirdLevelHierarchy)
    {
        QuoteCreationWebService.QuoteItems[] mNewquoteItemsList = new List<QuoteCreationWebService.QuoteItems>();
        
        for(Integer i=0; i < mNum; i++)
        { 
            QuoteCreationWebService.QuoteItems mNewquoteItem = new QuoteCreationWebService.QuoteItems();
            mNewquoteItem.MaterialNumber = MaterialNumber;
            mNewquoteItem.thirdLevelHierarchy = thirdLevelHierarchy;
            mNewquoteItem.Quantity = Quantity;
            mNewquoteItem.UnitPrice = UnitPrice;
            mNewquoteItemsList.add(mNewquoteItem);
            
        }
        return mNewquoteItemsList;
    }
    
    public static List<QuoteDeltaWebService.QuoteItems> createQuoteItemsDelta(Integer mNum,String MaterialNumber,Integer Quantity, Integer UnitPrice, String thirdLevelHierarchy)
    {
        QuoteDeltaWebService.QuoteItems[] mNewquoteItemsList = new List<QuoteDeltaWebService.QuoteItems>();
        
        for(Integer i=0; i < mNum; i++)
        { 
            QuoteDeltaWebService.QuoteItems mNewquoteItem = new QuoteDeltaWebService.QuoteItems();
            mNewquoteItem.MaterialNumber = MaterialNumber;
            mNewquoteItem.thirdLevelHierarchy = thirdLevelHierarchy;
            mNewquoteItem.Quantity = Quantity;
            mNewquoteItem.UnitPrice = UnitPrice;
            mNewquoteItemsList.add(mNewquoteItem);
            
        }
        return mNewquoteItemsList;
    }
    
    public static List<OrderCreationWebService.OrderItems> createOrderItemsCreate(Integer mNum,String MaterialNumber,Integer Quantity, Integer UnitPrice, String thirdLevelHierarchy)
    {
        OrderCreationWebService.OrderItems[] mNeworderItemsList = new List<OrderCreationWebService.OrderItems>();
        
        for(Integer i=0; i < mNum; i++)
        { 
            OrderCreationWebService.OrderItems mNeworderItem = new OrderCreationWebService.OrderItems();
            mNeworderItem.MaterialNumber = MaterialNumber;
            mNeworderItem.thirdLevelHierarchy = thirdLevelHierarchy;
            mNeworderItem.Quantity = Quantity;
            mNeworderItem.UnitPrice = UnitPrice;
            mNeworderItemsList.add(mNeworderItem);
            
        }
        return mNeworderItemsList;
    }
    
        public static List<OrderDeltaWebService.OrderItems> createOrderItemsDelta(Integer mNum,String MaterialNumber,Integer Quantity, Integer UnitPrice, String thirdLevelHierarchy)
    {
        OrderDeltaWebService.OrderItems[] mNeworderItemsList = new List<OrderDeltaWebService.OrderItems>();
        
        for(Integer i=0; i < mNum; i++)
        { 
            OrderDeltaWebService.OrderItems mNeworderItem = new OrderDeltaWebService.OrderItems();
            mNeworderItem.MaterialNumber = MaterialNumber;
            mNeworderItem.thirdLevelHierarchy = thirdLevelHierarchy;
            mNeworderItem.Quantity = Quantity;
            mNeworderItem.UnitPrice = UnitPrice;
            mNeworderItemsList.add(mNeworderItem);
            
        }
        return mNeworderItemsList;
    }
    
    public static List<Order> createOrderRecords(Integer mNum,Id accountId, Id opportunityId, Id pricebookId, Id ShippingAddress, String orderERPID, Boolean isInsert)
    {
        List<Order> mNewOrderList = new List<Order>();
        for(Integer i=0; i < mNum; i++)
        {
            Order mNewOrder = new Order();
            mNewOrder.Name = 'EEC Order - '+orderERPID;
            mNewOrder.Status = 'Draft';
            mNewOrder.EffectiveDate = system.today();
            mNewOrder.Pricebook2Id = pricebookId;
            mNewOrder.OpportunityId = opportunityId;
            mNewOrder.AccountId = accountId;
            mNewOrder.ERP_Id__c = orderERPID;
            mNewOrderList.add(mNewOrder);
        }
        
        if(isInsert == True)
        {
            insert mNewOrderList;
        }
        
        return mNewOrderList;
    }
    
    public static List<OrderItem> createOrderItemRecords(Integer mNum,Id orderId,Id productId, Id pricebookEntryID , Boolean isInsert)
    {
        List<OrderItem> mNewOrderItemList = new List<OrderItem>();
        
        for(Integer i=0; i < mNum; i++)
        {
            OrderItem mNewOrderItem = new OrderItem();
            mNewOrderItem.OrderId = orderId;
            mNewOrderItem.PricebookEntryId = pricebookEntryID;
            mNewOrderItem.Product2Id = productId;
            mNewOrderItem.Quantity = 2;
            mNewOrderItem.UnitPrice = 10;
            mNewOrderItemList.add(mNewOrderItem);
        }
        
        if(isInsert == True)
        {
            insert mNewOrderItemList;
        }
        
        return mNewOrderItemList;
    }
    
    public static List<Organization_Structure__c> createOrgStructureRecords(Integer mNum, String SaleOrg, String SalesOffice, String SalesGroup, String SalesDistrict, String Channel, String Division, Boolean SGT, Id TerritotyId, Boolean isInsert)
    {
        List<Organization_Structure__c> mOrgStructureList = new List<Organization_Structure__c>();
        
        for(Integer i=0; i < mNum; i++)
        {
            Organization_Structure__c mOrgStructure = new Organization_Structure__c();
            mOrgStructure.Sales_Organization__c = SaleOrg;
            mOrgStructure.Sales_Office__c = SalesOffice;
            mOrgStructure.Sales_Group__c = SalesGroup;
            mOrgStructure.Sales_District__c = SalesDistrict;
            mOrgStructure.Distribution_Channel__c = Channel;
            mOrgStructure.Division__c = Division;
            mOrgStructure.SGT__c = SGT;
            mOrgStructure.Territoty_ID__c = TerritotyId;
            mOrgStructureList.add(mOrgStructure);
        }
        
        if(isInsert == True)
        {
            insert mOrgStructureList;
        }
        
        return mOrgStructureList;
    }
    
    public static List<Sales_Area_Detail__c> createSalesAreaRecords(Integer mNum, Id AccountId, Id OrgStructureId, Boolean isInsert)
    {
        List<Sales_Area_Detail__c> mSalesAreaList = new List<Sales_Area_Detail__c>();
        
        for(Integer i=0; i < mNum; i++)
        {
            Sales_Area_Detail__c mSalesArea = new Sales_Area_Detail__c();
            mSalesArea.Name = 'mSalesArea '+i;
            mSalesArea.Account__c = AccountId;
            mSalesArea.Organization_Structure__c = OrgStructureId;
            mSalesAreaList.add(mSalesArea);
        }
        
        if(isInsert == True)
        {
            insert mSalesAreaList;
        }
        
        return mSalesAreaList;
    }
}