force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Address</relationshipLabel>
    <relationshipName>Shipping_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_ID__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DLV{00000000}</displayFormat>
        <label>Delivery ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Document_Date__c.field-meta.xml
<CustomField>
    <fullName>Document_Date__c</fullName>
    <label>Document Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Loading_Date__c.field-meta.xml
<CustomField>
    <fullName>Loading_Date__c</fullName>
    <label>Loading Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Picking_Date__c.field-meta.xml
<CustomField>
    <fullName>Picking_Date__c</fullName>
    <label>Picking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Planned_Good_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Good_Issue_Date__c</fullName>
    <label>Planned Good Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Organization</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/SAP_Delivery_Order_No__c.field-meta.xml
<CustomField>
    <fullName>SAP_Delivery_Order_No__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship-To</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery Created</fullName>
                <default>true</default>
                <label>Delivery Created</label>
            </value>
            <value>
                <fullName>Picking</fullName>
            </value>
            <value>
                <fullName>Packing</fullName>
            </value>
            <value>
                <fullName>Goods Issued</fullName>
            </value>
            <value>
                <fullName>Proof of Delivery</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Status_Detail__c.field-meta.xml
<CustomField>
    <fullName>Status_Detail__c</fullName>
    <label>Status Detail</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Not yet processed</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Partially processed</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Completely processed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Tracking_No__c.field-meta.xml
<CustomField>
    <fullName>Tracking_No__c</fullName>
    <label>Tracking No.</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Transportation_Plan_Date__c.field-meta.xml
<CustomField>
    <fullName>Transportation_Plan_Date__c</fullName>
    <label>Transportation Plan Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/Delivery_Product__c.object-meta.xml
<CustomObject>
    <label>Delivery Product</label>
    <nameField>
        <displayFormat>DP{00000000}</displayFormat>
        <label>Delivery Products No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Product__c/fields/Actual_Goods_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Goods_Issue_Date__c</fullName>
    <label>Actual Goods Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipName>Delivery_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Delivery_Qty__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Qty__c</fullName>
    <label>Quantity to Deliver</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Delivery_Qty_UOM__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Qty_UOM__c</fullName>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SAP_Measurement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/DO_Item_No__c.field-meta.xml
<CustomField>
    <fullName>DO_Item_No__c</fullName>
    <label>DO Item No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Gross_Weight__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Item_Status__c.field-meta.xml
<CustomField>
    <fullName>Item_Status__c</fullName>
    <label>Item Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery Created</fullName>
                <default>true</default>
                <label>Delivery Created</label>
            </value>
            <value>
                <fullName>Picking</fullName>
            </value>
            <value>
                <fullName>Packing</fullName>
            </value>
            <value>
                <fullName>Goods Issued</fullName>
            </value>
            <value>
                <fullName>Proof Of Delivery</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Item_Status_Detail__c.field-meta.xml
<CustomField>
    <fullName>Item_Status_Detail__c</fullName>
    <label>Item Status Detail</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Not yet processed</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Partially processed</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Completely processed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Net_Weight__c.field-meta.xml
<CustomField>
    <fullName>Net_Weight__c</fullName>
    <label>Net Weight</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Order_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Order_Item_No__c</fullName>
    <label>Order Item No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Delivery Products</relationshipLabel>
    <relationshipName>Delivery_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Planned_Goods_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Goods_Issue_Date__c</fullName>
    <label>Planned Goods Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <label>Material Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Weight_Unit__c.field-meta.xml
<CustomField>
    <fullName>Weight_Unit__c</fullName>
    <label>Weight Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SAP_Measurement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Actual_Goods_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Goods_Issue_Date__c</fullName>
    <description>Latest Actual Goods Issue Date</description>
    <inlineHelpText>Latest Actual Goods Issue Date</inlineHelpText>
    <label>Actual Goods Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Line_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_No__c</fullName>
    <label>Line Item No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Loading_Date__c.field-meta.xml
<CustomField>
    <fullName>Loading_Date__c</fullName>
    <label>Loading Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Created</fullName>
                <default>true</default>
                <label>Order Created</label>
            </value>
            <value>
                <fullName>Delivery In Process</fullName>
            </value>
            <value>
                <fullName>Partially Delivered</fullName>
            </value>
            <value>
                <fullName>Fully Delivered</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Transportation_Plan_Date__c.field-meta.xml
<CustomField>
    <fullName>Transportation_Plan_Date__c</fullName>
    <label>Transportation Plan Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/SAP_Measurement.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue><fullName>P1</fullName><label>%</label></customValue>
<customValue><fullName>2M</fullName><label>CMS</label></customValue>
<customValue><fullName>2X</fullName><label>000</label></customValue>
<customValue><fullName>4G</fullName><label>µL</label></customValue>
<customValue><fullName>4O</fullName><label>µF</label></customValue>
<customValue><fullName>4T</fullName><label>IB</label></customValue>
<customValue><fullName>AMP</fullName><label>A</label></customValue>
<customValue><fullName>A87</fullName><label>GOH</label></customValue>
<customValue><fullName>A93</fullName><label>GM3</label></customValue>
<customValue><fullName>W08</fullName><label>ADH</label></customValue>
<customValue><fullName>WE3</fullName><label>AFS</label></customValue>
<customValue><fullName>B34</fullName><label>KD3</label></customValue>
<customValue><fullName>B45</fullName><label>QML</label></customValue>
<customValue><fullName>B47</fullName><label>NI</label></customValue>
<customValue><fullName>B73</fullName><label>MN</label></customValue>
<customValue><fullName>B75</fullName><label>MGO</label></customValue>
<customValue><fullName>B78</fullName><label>MHV</label></customValue>
<customValue><fullName>B84</fullName><label>µA</label></customValue>
<customValue><fullName>BG</fullName><label>BAG</label></customValue>
<customValue><fullName>BAR</fullName><label>BAR</label></customValue>
<customValue><fullName>BO</fullName><label>BT</label></customValue>
<customValue><fullName>BOX</fullName><label>BOX</label></customValue>
<customValue><fullName>BYT</fullName><label>BYT</label></customValue>
<customValue><fullName>C10</fullName><label>RF</label></customValue>
<customValue><fullName>C38</fullName><label>M/L</label></customValue>
<customValue><fullName>C39</fullName><label>NA</label></customValue>
<customValue><fullName>2J</fullName><label>C3S</label></customValue>
<customValue><fullName>C41</fullName><label>R-U</label></customValue>
<customValue><fullName>C56</fullName><label>NMM</label></customValue>
<customValue><fullName>CMQ</fullName><label>CCM</label></customValue>
    <masterLabel>SAP Measurement</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DeliveryCreationWebService.cls
global class DeliveryCreationWebService
{    
    global class DeliveryItem
    {
        webservice	Integer	doLineItemNo; //10,20,30
        webservice	Integer	orderLineItemNo; //10,20,30
        webservice	String	orderERPID; 
        webservice	String	materialNumber; //D009
        webservice	Decimal	deliveryQuantity; //10
        webservice	String	uom; //UNT
        webservice	Decimal	netWeight;
        webservice	Decimal	grossWeight;
        webservice	String	weightUnit;
        webservice	String	pickingStatus; //A,B,C
        webservice	String	packingStatus; //A,B,C
        webservice	String	materialDescription;
    }
    
    global class Results
    {
        webservice boolean success;
        webservice String errorMessage;
    }
    
    public static DeliveryCreationWebService.Results result =  new DeliveryCreationWebService.Results();
    
    webservice static DeliveryCreationWebService.Results DeliveryCreation(
        String deliveryERPID, String trackingNo, Date plannedGIDate, Date actualGIDate, Date loadingDate, Date pickingDate, Date transPlanningDate,
        String shipToStreet, String shipToCity, String ShipToState, String shipToPostalCode, String shipToCountry, String accountERPID,
        String pickingStatus, String packingStatus, Date deliveryDate, Date documentDate, String saleOrgCode, String ShipToERPID, String carrierName ,List<DeliveryItem> DeliveryItems)
        
    {
        Id deliveryId;
        Integer deliveryItemSuccess = 0;
        Map<String,Id> orderItemsMap = new Map<String,Id>();
        List<String> allDeliveryOrderERPIds = new List<String>();
        List<OrderItem> allOrderItems = new List<OrderItem>();
        List<Delivery_Product__c> deliveryProducts = new List<Delivery_Product__c>();
        result.success = false;
        Boolean validatedItems = false;
        
        if (!DeliveryItems.isEmpty())
        {
            
            for(DeliveryCreationWebService.DeliveryItem item : DeliveryItems)
            {
                allDeliveryOrderERPIds.add(item.orderERPID);
            }
            
            allOrderItems = [SELECT Id, Line_Item_No__c, OrderId, Order.ERP_Id__c FROM OrderItem WHERE Order.ERP_Id__c IN: allDeliveryOrderERPIds];
            
            if (!allOrderItems.isEmpty())
            {
                system.debug('allOrderItems '+allOrderItems);
                for(DeliveryCreationWebService.DeliveryItem deliveryItem : DeliveryItems)
                {
                    validatedItems = false;
                    for(OrderItem orderItem : allOrderItems)
                    {
                        if(deliveryItem.orderERPID == orderItem.Order.ERP_Id__c && deliveryItem.orderLineItemNo == orderItem.Line_Item_No__c)
                        {
                            validatedItems = true;
                            orderItemsMap.put(deliveryItem.orderERPID + deliveryItem.orderLineItemNo, orderItem.Id);
                            break;
                        }
                    }
                    
                    if(validatedItems == false)
                    {
                        result.errorMessage = 'Cannot find OrderItem No. '+ deliveryItem.orderLineItemNo+' orderERPID: '+deliveryItem.orderERPID+ ' on '+ deliveryERPID;
                        createErrorMessage(result.errorMessage, deliveryERPID, accountERPID);
                    }
                }
            }
            else
            {
                result.errorMessage = 'Cannot find Order ERP Id : '+ allDeliveryOrderERPIds;
                createErrorMessage(result.errorMessage, deliveryERPID, accountERPID);
            }
            
            
            List<Address__c> shipTo = [SELECT Id FROM Address__c WHERE ERP_Id__c =: shipToERPID LIMIT 1];
            system.debug('shipTo : '+shipTo);
            
            if (validatedItems == true)
            {
                Savepoint sp = Database.setSavepoint(); 
                //-----------Create Delivery__c------------------//
                Delivery__c delivery = new Delivery__c();
                delivery.SAP_Delivery_Order_No__c = deliveryERPID;
                delivery.Tracking_No__c = trackingNo;
                delivery.Planned_Good_Issue_Date__c = plannedGIDate;
                delivery.Actual_Goods_Issue_Date__c = actualGIDate;
                delivery.Loading_Date__c = loadingDate;
                delivery.Picking_Date__c = pickingDate;
                if(transPlanningDate == date.valueOf('0002-11-30')) delivery.Transportation_Plan_Date__c = null;
                else delivery.Transportation_Plan_Date__c = transPlanningDate;
                delivery.Street__c = shipToStreet;
                delivery.City__c = shipToCity;
                delivery.State__c = ShipToState;
                delivery.Postal_Code__c = shipToPostalCode;
                delivery.Country__c = shipToCountry;
                delivery.Delivery_Date__c = deliveryDate;
                delivery.Document_Date__c = documentDate;
                delivery.Sales_Organization__c = saleOrgCode;
                if(!shipTo.isEmpty()) delivery.Ship_To__c = shipTo[0].Id; // if empty, leave it blank
                delivery.Account__r = new Account(ERP_Id__c = accountERPID);
                delivery.Carrier_Name__c  = carrierName;
                
                system.debug('PackingStatus '+PackingStatus);
                system.debug('PickingStatus '+PickingStatus);
                if(PackingStatus != '' && PackingStatus != 'A')
                {
                    delivery.Status__c = 'Packing';
                    delivery.Status_Detail__c = PackingStatus;
                }
                else if(PickingStatus != '' && PickingStatus != 'A')
                {
                    delivery.Status__c = 'Picking';
                    delivery.Status_Detail__c = PickingStatus;
                }
                else
                {
                    delivery.Status__c = 'Delivery Created';
                    delivery.Status_Detail__c = null;
                }
                
                system.debug('new Delivery '+delivery);
                Database.SaveResult deliveryResult = Database.insert(delivery, false);
                if (deliveryResult.isSuccess())
                {
                    deliveryId = deliveryResult.getId();
                    System.debug('Delivery created successfully: ' + deliveryId);
                    //-----------Create Delivery Line Items------------------//
                    if (!orderItemsMap.isEmpty())
                    {
                        for(DeliveryCreationWebService.DeliveryItem item : DeliveryItems)
                        {
                            if(orderItemsMap.containsKey(item.orderERPID + item.orderLineItemNo))
                            {
                                system.debug('item PackingStatus '+item.PackingStatus);
                                system.debug('item PickingStatus '+item.PickingStatus);
                                Delivery_Product__c deliveryProduct = new Delivery_Product__c();
                                deliveryProduct.Delivery__c = deliveryId;
                                deliveryProduct.Order_Product__c = orderItemsMap.get(item.orderERPID + item.orderLineItemNo);
                                deliveryProduct.Order_Item_No__c = item.orderLineItemNo;
                                deliveryProduct.DO_Item_No__c = item.doLineItemNo;
                                deliveryProduct.Product_ID__c  = item.materialNumber;
                                deliveryProduct.Product_Description__c  = item.materialDescription;
                                deliveryProduct.Delivery_Qty__c = item.deliveryQuantity;
                                deliveryProduct.Delivery_Qty_UOM__c = item.uom;
                                deliveryProduct.Net_Weight__c = item.netWeight;
                                deliveryProduct.Gross_Weight__c = item.grossWeight;
                                deliveryProduct.Weight_Unit__c = item.weightUnit;
                                deliveryProduct.Planned_Goods_Issue_Date__c = plannedGIDate;
                                deliveryProduct.Actual_Goods_Issue_Date__c = actualGIDate;
                                deliveryProduct.Delivery_Item_ID__c = deliveryERPID + item.doLineItemNo + item.orderERPID + item.orderLineItemNo;
                                
                                if(item.PackingStatus != '' && item.PackingStatus != 'A')
                                {
                                    deliveryProduct.Item_Status__c = 'Packing';
                                    deliveryProduct.Item_Status_Detail__c = item.PackingStatus;
                                }
                                else if(item.PickingStatus != '' && item.PickingStatus != 'A')
                                {
                                    deliveryProduct.Item_Status__c = 'Picking';
                                    deliveryProduct.Item_Status_Detail__c = item.PickingStatus;
                                }
                                else
                                {
                                    deliveryProduct.Item_Status__c = 'Delivery Created';
                                    deliveryProduct.Item_Status_Detail__c = null;
                                }
                                
                                deliveryProducts.add(deliveryProduct);
                            }
                            /*else
{
result.errorMessage = 'Cannot find OrderItem No. : '+ item.orderLineItemNo+ ' on '+ item.orderERPID;
Database.rollback(sp);
createErrorMessage(result.errorMessage, deliveryERPID, accountERPID);
}*/
                        }
                        
                        if(!deliveryProducts.isEmpty()){
                            Database.SaveResult[] deliveryItemResultList = Database.insert(deliveryProducts, false);
                            for (Database.SaveResult sr : deliveryItemResultList) 
                            {
                                if (sr.isSuccess())
                                {
                                    deliveryItemSuccess = deliveryItemSuccess+1;
                                    System.debug('DeliveryItems created successfully: ' + sr.getId());
                                }
                                else
                                {              
                                    for(Database.Error err : sr.getErrors())
                                    {                 
                                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                                        System.debug('DeliveryItems fields that affected this error: ' + err.getFields());
                                        result.errorMessage = 'Create DeliveryItems '+err.getStatusCode() + ': ' + err.getMessage();
                                    }
                                    Database.rollback(sp);
                                    createErrorMessage(result.errorMessage, deliveryERPID, accountERPID);
                                }
                            }
                            
                            if(deliveryItemSuccess == deliveryProducts.size())
                            {
                                result.success = true;
                                List<Order> orders = [SELECT Id, Order_Updated_Date__c FROM Order WHERE ERP_Id__c IN: allDeliveryOrderERPIds];
                                for(Order order : orders)
                                {
                                    order.Order_Updated_Date__c = DateTime.now();
                                }
                                system.debug('Update Order_Updated_Date__c '+orders);
                                update orders;
                            }
                        }
                    }
                    
                }
                else // Create Delivery Fail
                {              
                    for(Database.Error err : deliveryResult.getErrors())
                    {                 
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Delivery fields that affected this error: ' + err.getFields());
                        result.errorMessage = 'Create Delivery '+err.getStatusCode() + ': ' + err.getMessage();
                    }
                    Database.rollback(sp);
                    createErrorMessage(result.errorMessage, deliveryERPID, accountERPID);
                }
            }
            else createErrorMessage(result.errorMessage, deliveryERPID, accountERPID);
        }
        else
        {
            result.errorMessage = 'There is no DeliveryItems';
            createErrorMessage(result.errorMessage, deliveryERPID, accountERPID);
        }
        

        System.debug('ReturnValue '+result);
        return result;  
    }
    
    public static void createErrorMessage(String errMessage, String deliveryERPID, String accountERPID)
    {
        try
        {
            Error_Message__c mError = new Error_Message__c();
            mError.Scenario__c = 'Delivery Order Creation';
            mError.Error_Message_Detail__c = errMessage;
            mError.Delivery_ERP_ID__c = deliveryERPID;
            mError.Account_ERP_ID__c = accountERPID;
            insert mError;
        }
        catch (DmlException e)
        {
            System.debug(e.getMessage() + ': ' + e.getLineNumber());
        }
    }
}