force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Address</relationshipLabel>
    <relationshipName>Shipping_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_ID__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DLV{00000000}</displayFormat>
        <label>Delivery ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Organization</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/SAP_Delivery_Order_No__c.field-meta.xml
<CustomField>
    <fullName>SAP_Delivery_Order_No__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/Delivery_Product__c.object-meta.xml
<CustomObject>
    <label>Delivery Product</label>
    <nameField>
        <displayFormat>DP{00000000}</displayFormat>
        <label>Delivery Products No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Product__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipName>Delivery_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/DO_Item_No__c.field-meta.xml
<CustomField>
    <fullName>DO_Item_No__c</fullName>
    <label>DO Item No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Order_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Order_Item_No__c</fullName>
    <label>Order Item No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Delivery Products</relationshipLabel>
    <relationshipName>Delivery_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV{0000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_ID__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Organization</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Material_Number__c/Material_Number__c.object-meta.xml
<CustomObject>
    <label>Material Number</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Number</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Number__c/fields/ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_ID__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Line_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_No__c</fullName>
    <label>Line Item No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Material_Number__c</description>
    <label>Material Number</label>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/Organization_Structure__c.object-meta.xml
<CustomObject>
    <label>Organization Structure</label>
    <nameField>
        <displayFormat>TRTY-{00000}</displayFormat>
        <label>Organization Structure Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Structure__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Area_Detail__c/Sales_Area_Detail__c.object-meta.xml
<CustomObject>
    <label>Sales Area Detail</label>
    <nameField>
        <label>Organization Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Area_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Area Details</relationshipLabel>
    <relationshipName>Sales_Area_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Area_Detail__c/fields/Organization_Structure__c.field-meta.xml
<CustomField>
    <fullName>Organization_Structure__c</fullName>
    <label>Organization Structure</label>
    <referenceTo>Organization_Structure__c</referenceTo>
    <relationshipLabel>Sales Area Details</relationshipLabel>
    <relationshipName>Sales_Area_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Organization__c/Sales_Organization__c.object-meta.xml
<CustomObject>
    <label>Sales Organization</label>
    <nameField>
        <label>Sales Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Organization_User__c/Sales_Organization_User__c.object-meta.xml
<CustomObject>
    <label>Sales Organization User</label>
    <nameField>
        <label>Sales Organization User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organization Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderDeltaWebService_Test.cls
@isTest
private class OrderDeltaWebService_Test {
    static List<Account> mAccounts;
    static User mUser;
    static List<Address__c> mShipTos;
    static List<Sales_Organization__c> mSalesOrgs;
    static List<Sales_Organization_User__c> mSalesOrgUsers;
    static List<Opportunity> mOpportunities;
    static List<Material_Number__c> mMaterials;
    static List<String> materialNumbers = new List<String>();
    static List<Product2> mNewProducts2;
    Static List<PricebookEntry> mNewPricebookEntries;
    static List<Quote> mNewQuotes;
    static List<QuoteLineItem> mNewQuoteLineItems ;
    static List<Order> mNewOrders;
    static List<OrderItem> mNewOrderItem ;
    static List<OrderDeltaWebService.OrderItems> mNeworderItems = new List<OrderDeltaWebService.OrderItems>();
    static Id STDPriceBookId;
    static Territory2Model terrModel;
    static Territory2 objTerr;
    static List<Territory2Type> terriType;
    static List<Organization_Structure__c> mOrgStructure;
    static List<Sales_Area_Detail__c> mSalesArea;
    static OrderDeltaWebService.AdditionalInfo mAdditionalInfo = new OrderDeltaWebService.AdditionalInfo();

    
    static void setupTestData(){
        
        Profile mProfile = [SELECT Id FROM Profile WHERE Name = 'Integration']; 
        insert mUser = new User(Alias = 'standt', Email='Integration@testorg.com', 
                         EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                         LocaleSidKey='en_US', ProfileId = mProfile.Id, 
                         TimeZoneSidKey='America/Los_Angeles', UserName='Integration@testorg.com', ERP_Id__c = 'user123');
        
        System.runAs (new User(Id = UserInfo.getUserId())){
            terriType = [SELECT id, DeveloperName from Territory2Type where DeveloperName = 'Managed_Accounts'];
            terrModel = [SELECT id, DeveloperName,State from Territory2Model where DeveloperName = 'Weir_Minerals'];
            insert objTerr = new Territory2(DeveloperName = 'TestTerritory', Territory2ModelId = terrModel.Id, Name='AM1_AM01_GB01', Territory2TypeId=terriType[0].Id);
        }
        
        System.runAs(mUser) 
        {
            STDPriceBookId = TestUtility.createSTDPriceBookRecords();
            mAccounts = TestUtility.createAccountRecords(1, True);
            mShipTos = TestUtility.createShippingRecords(1, mAccounts[0].id, True);
            mSalesOrgs = TestUtility.createSalesOrgRecords(1, 'GB01', True);
            mSalesOrgUsers = TestUtility.createSalesOrgUserRecords(1, mUser.Id, mSalesOrgs[0].id, True);
            mOrgStructure = TestUtility.createOrgStructureRecords(1,'GB01','AM01','AM1', null, '30', '00', True, objTerr.Id, True);
            mSalesArea = TestUtility.createSalesAreaRecords(1, mAccounts[0].Id, mOrgStructure[0].id, True);
            mOpportunities = TestUtility.createOpportunityRecords(1, mAccounts[0].id, mShipTos[0].id, mSalesOrgUsers[0].id, STDPriceBookId, 'AUD','30', '00',True, True);
            mMaterials = TestUtility.createMaterialRecords(2, 'Mat123', True);
            mNewProducts2 = TestUtility.createProductRecords(1, 'Z0001S0001', True);
            mNewPricebookEntries = TestUtility.createPricebookEntryRecords(1, mNewProducts2[0].Id, STDPriceBookId,'AUD', True);
            mNewQuotes = TestUtility.createQuoteRecords(1, mOpportunities[0].id, STDPriceBookId, mShipTos[0].id, 'QT1234', True);
            mNewOrders = TestUtility.createOrderRecords(1, mAccounts[0].id, mOpportunities[0].id, STDPriceBookId, mShipTos[0].id, 'OR1234', True);
            mAdditionalInfo.shippingCondition = '01';
            mAdditionalInfo.incoterm1 = 'AIR';
            mAdditionalInfo.incoterm2 = 'Test';
            mAdditionalInfo.paymentTerm = '0001';
            mAdditionalInfo.quotedMargin = 1;
            mAdditionalInfo.application = 'Z07';
            mAdditionalInfo.integratedSolution = 'YES';
            mAdditionalInfo.otherStrategicInitiatives = '01';
            mAdditionalInfo.important = true;
            mAdditionalInfo.managedByProjectTeams = true;
            mAdditionalInfo.orderCreatedDate = System.today();
            mAdditionalInfo.orderReceptionDate = System.today();
            mAdditionalInfo.requestedDeliveryDate = System.today();
            mAdditionalInfo.customerPONumber = '12334';
            mAdditionalInfo.onHold = true;
            mAdditionalInfo.saleOrgCode = 'GB01';
            
            mNewOrders[0].CurrencyIsoCode = 'AUD';
            update mNewOrders;
            
            OrderItem mNewOrderItem = new OrderItem();
            mNewOrderItem.OrderId = mNewOrders.get(0).Id;
            mNewOrderItem.PricebookEntryId = mNewPricebookEntries.get(0).Id;
            mNewOrderItem.Product2Id = mNewProducts2.get(0).Id;
            mNewOrderItem.Material_Number__c = mMaterials.get(0).Id;
            mNewOrderItem.Quantity = 2;
            mNewOrderItem.UnitPrice = 10;
            mNewOrderItem.Line_Item_No__c = 10;
            insert mNeworderItem;
            
            Delivery__c delivery = new Delivery__c();
            delivery.SAP_Delivery_Order_No__c = '6000020345';
            delivery.Sales_Organization__c = 'GB01';
            delivery.Account__c = mAccounts.get(0).Id;
            delivery.SAP_Delivery_Order_No__c = 'DEV0001';
            insert delivery;
            

            Delivery_Product__c deliveryItem = new Delivery_Product__c();
            deliveryItem.DO_Item_No__c = 10;
            deliveryItem.Order_Item_No__c = 10;
            deliveryItem.Order_Product__c = mNeworderItem.Id;
            deliveryItem.Delivery__c = delivery.Id;
            insert deliveryItem;
            
            Invoice__c invoice = new Invoice__c ();
            invoice.Sales_Organization__c  = 'GB01';
            invoice.ERP_ID__c  = 'IN0001';
            insert invoice;
            
            Invoice_Item__c invoiceItem = new Invoice_Item__c();
            invoiceItem.Invoice__c = invoice.Id;
            invoiceItem.Invoice_Item_No__c = 10;
            invoiceItem.Delivery_Item__c = deliveryItem.Id;
            invoiceItem.Order_Item__c = mNeworderItem.Id;
            insert invoiceItem;
        }
        
    }
    @isTest static void OrderDeltaSuccess()
    {              
        setupTestData();
        mNeworderItems = TestUtility.createOrderItemsDelta(1,mMaterials[0].Name,2,3,'Z0001S0001');
        mNeworderItems[0].lineItemNo = 10;
        Test.startTest();
        OrderDeltaWebService.Results result = OrderDeltaWebService.OrderDelta(
            mAccounts[0].ERP_Id__c, mUser.ERP_Id__c, mShipTos[0].ERP_Id__c, System.today(), 
            'AUD','Order Description','OR1234','Y41CLNT331',
            'Street','City','QLD','PostalCode','AU', 'user123','user123',
            mAdditionalInfo,
            mNeworderItems);
        Test.stopTest();
    }
    
    @isTest static void OrderDeltaNo3rdLevel()
    {              
        setupTestData();
        mNeworderItems = TestUtility.createOrderItemsDelta(1,mMaterials[0].Name,2,3,null);
        Test.startTest();
        OrderDeltaWebService.Results result = OrderDeltaWebService.OrderDelta(
            mAccounts[0].ERP_Id__c, mUser.ERP_Id__c, mShipTos[0].ERP_Id__c, System.today(), 
            'AUD','Order Description','OR1234','Y41CLNT331',
            'Street','City','QLD','PostalCode','AU', 'user123','user123',
            mAdditionalInfo,
            mNeworderItems);
        Test.stopTest();
    }
    
    @isTest static void OrderDeltaDeleteAllItems()
    {              
        setupTestData();
        Test.startTest();
        OrderDeltaWebService.Results result = OrderDeltaWebService.OrderDelta(
            mAccounts[0].ERP_Id__c, mUser.ERP_Id__c, mShipTos[0].ERP_Id__c, System.today(), 
            'AUD','Order Description','OR1234','Y41CLNT331',
            'Street','City','QLD','PostalCode','AU', 'user123','user123',
            mAdditionalInfo,
            mNeworderItems);
        Test.stopTest();
    }
    
    @isTest static void OrderDeltaShipToNotValidated()
    {              
        setupTestData();
        Test.startTest();
        OrderDeltaWebService.Results result = OrderDeltaWebService.OrderDelta(
            null, mUser.ERP_Id__c, 'mShipTos[0].ERP_Id__c', System.today(), 
            'AUD','Order Description','OR1234','Y41CLNT331',
            'Street','City','QLD','PostalCode','AU', 'user123','user123',
            mAdditionalInfo,
            mNeworderItems);
        Test.stopTest();
    }
    
    @isTest static void OrderFail()
    {              
        setupTestData();
        mNeworderItems = TestUtility.createOrderItemsDelta(1,mMaterials[0].Name,2,3,'Z0003S0012CC000003');
        Test.startTest();
        OrderDeltaWebService.Results result = OrderDeltaWebService.OrderDelta(
            mAccounts[0].ERP_Id__c, mUser.ERP_Id__c, mShipTos[0].ERP_Id__c, System.today(), 
            'AUD','Order Description','OR1234','Y41CLNT331',
            'Street','City','QLD','PostalCode9999999999999999','AU', 'user123','user123',
            mAdditionalInfo,
            mNeworderItems);
        Test.stopTest();
    }
    
    @isTest static void OrderItemNotFoundPBEntry()
    {              
        setupTestData();
        mNeworderItems = TestUtility.createOrderItemsDelta(1,mMaterials[0].Name,2,3,'Z0003S0012CC000003');
        Test.startTest();
        OrderDeltaWebService.Results result = OrderDeltaWebService.OrderDelta(
            mAccounts[0].ERP_Id__c, mUser.ERP_Id__c, mShipTos[0].ERP_Id__c, System.today(), 
            'AUD','Order Description','OR1234','Y41CLNT331',
            'Street','City','QLD','PostalCode','AU', 'user123','user123',
            mAdditionalInfo,
            mNeworderItems);
        Test.stopTest();
    }
    
    @isTest static void OrderItemFail()
    {              
        setupTestData();
        mNeworderItems = TestUtility.createOrderItemsDelta(1,mMaterials[0].Name,null,3,'Z0001S0001');
        Test.startTest();
        OrderDeltaWebService.Results result = OrderDeltaWebService.OrderDelta(
            mAccounts[0].ERP_Id__c, mUser.ERP_Id__c, mShipTos[0].ERP_Id__c, System.today(), 
            'USD','Order Description','OR1234','Y41CLNT331',
            'Street','City','QLD','PostalCode','AU', 'user123','user123',
            mAdditionalInfo,
            mNeworderItems);
        Test.stopTest();
    }
}