force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_ID__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Material_Number__c/Material_Number__c.object-meta.xml
<CustomObject>
    <label>Material Number</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Number</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Number__c/fields/ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_ID__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Material_Number__c/fields/Material_Status__c.field-meta.xml
<CustomField>
    <fullName>Material_Status__c</fullName>
    <label>Material Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Material_Number__c/fields/X3rd_Level_Product_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Level_Product_Hierarchy__c</fullName>
    <label>Product Hierarchy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Z0001</fullName>
            </value>
            <value>
                <fullName>Z0001S0001</fullName>
            </value>
            <value>
                <fullName>Z0001S0001CP000002</fullName>
            </value>
            <value>
                <fullName>Z0001S0001CP000004</fullName>
            </value>
            <value>
                <fullName>Z0001S0001CP000006</fullName>
            </value>
            <value>
                <fullName>Z0001S0001CP000007</fullName>
            </value>
            <value>
                <fullName>Z0001S0001CP000008</fullName>
            </value>
            <value>
                <fullName>Z0001S0001CP000009</fullName>
            </value>
            <value>
                <fullName>Z0001S0001CP000010</fullName>
            </value>
            <value>
                <fullName>Z0001S0001PU000001--OEM / SLURRY PUMPS / PD PUMPS</fullName>
                <isActive>false</isActive>
                <label>Z0001S0001PU000001--OEM / SLURRY PUMPS / PD PUMPS</label>
            </value>
            <value>
                <fullName>Z0001S0001PU000002--OEM / SLURRY PUMPS / HORIZONTAL PUMPS</fullName>
                <isActive>false</isActive>
                <label>Z0001S0001PU000002--OEM / SLURRY PUMPS / HORIZONTAL PUMPS</label>
            </value>
            <value>
                <fullName>Z0001S0001PU000003--OEM / SLURRY / VERTICLE TURBINE PUMPS</fullName>
                <isActive>false</isActive>
                <label>Z0001S0001PU000003--OEM / SLURRY / VERTICLE TURBINE PUMPS</label>
            </value>
            <value>
                <fullName>Z0001S0001PU000004--OEM / SLURRY PUMPS / VERTICAL PUMPS</fullName>
                <isActive>false</isActive>
                <label>Z0001S0001PU000004--OEM / SLURRY PUMPS / VERTICAL PUMPS</label>
            </value>
            <value>
                <fullName>Z0001S0001PU000005--OEM / SLURRY PUMPS / SUBMERSIBLE PUMPS</fullName>
                <isActive>false</isActive>
                <label>Z0001S0001PU000005--OEM / SLURRY PUMPS / SUBMERSIBLE PUMPS</label>
            </value>
            <value>
                <fullName>Z0001S0001PU000006--OEM / SLURRY PUMPS / PUMP ANCILLIARIES</fullName>
                <isActive>false</isActive>
                <label>Z0001S0001PU000006--OEM / SLURRY PUMPS / PUMP ANCILLIARIES</label>
            </value>
            <value>
                <fullName>Z0001S0001PU000007--OEM / SLURRY PUMPS / OTHER PUMPS</fullName>
                <isActive>false</isActive>
                <label>Z0001S0001PU000007--OEM / SLURRY PUMPS / OTHER PUMPS</label>
            </value>
            <value>
                <fullName>Z0001S0002</fullName>
            </value>
            <value>
                <fullName>Z0001S0002VA000001</fullName>
            </value>
            <value>
                <fullName>Z0001S0002VA000001--OEM / VALVES / PINCH VALVES</fullName>
                <isActive>false</isActive>
                <label>Z0001S0002VA000001--OEM / VALVES / PINCH VALVES</label>
            </value>
            <value>
                <fullName>Z0001S0002VA000002--OEM / VALVES / KNIFEGATE VALVES</fullName>
                <isActive>false</isActive>
                <label>Z0001S0002VA000002--OEM / VALVES / KNIFEGATE VALVES</label>
            </value>
            <value>
                <fullName>Z0001S0002VA000003</fullName>
            </value>
            <value>
                <fullName>Z0001S0002VA000003--OEM / VALVES / VALVE ANCILLIARIES</fullName>
                <isActive>false</isActive>
                <label>Z0001S0002VA000003--OEM / VALVES / VALVE ANCILLIARIES</label>
            </value>
            <value>
                <fullName>Z0001S0002VA000004</fullName>
            </value>
            <value>
                <fullName>Z0001S0002VA000004--OEM / VALVES / OTHER VALVES</fullName>
                <isActive>false</isActive>
                <label>Z0001S0002VA000004--OEM / VALVES / OTHER VALVES</label>
            </value>
            <value>
                <fullName>Z0001S0002VA000005</fullName>
            </value>
            <value>
                <fullName>Z0001S0002VA000006</fullName>
            </value>
            <value>
                <fullName>Z0001S0002VA000007</fullName>
            </value>
            <value>
                <fullName>Z0001S0003</fullName>
            </value>
            <value>
                <fullName>Z0001S0003OT000008</fullName>
            </value>
            <value>
                <fullName>Z0001S0003OT000009</fullName>
            </value>
            <value>
                <fullName>Z0002S0002VA000001</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opp_Transfer_Owner__c/Opp_Transfer_Owner__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Opp - Transfer Owner</label>
</CustomObject>

force-app/main/default/objects/Opp_Transfer_Owner__c/fields/Non_SGT_Profile__c.field-meta.xml
<CustomField>
    <fullName>Non_SGT_Profile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non SGT Profile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opp_Transfer_Owner__c/fields/SGT_Profile__c.field-meta.xml
<CustomField>
    <fullName>SGT_Profile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SGT Profile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Number</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Material is obsolete</errorMessage>
        <filterItems>
            <field>Material_Number__c.Material_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/Organization_Structure__c.object-meta.xml
<CustomObject>
    <label>Organization Structure</label>
    <nameField>
        <displayFormat>TRTY-{00000}</displayFormat>
        <label>Organization Structure Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Structure__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Area_Detail__c/Sales_Area_Detail__c.object-meta.xml
<CustomObject>
    <label>Sales Area Detail</label>
    <nameField>
        <label>Organization Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Area_Detail__c/fields/Organization_Structure__c.field-meta.xml
<CustomField>
    <fullName>Organization_Structure__c</fullName>
    <label>Organization Structure</label>
    <referenceTo>Organization_Structure__c</referenceTo>
    <relationshipLabel>Sales Area Details</relationshipLabel>
    <relationshipName>Sales_Area_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Organization__c/Sales_Organization__c.object-meta.xml
<CustomObject>
    <label>Sales Organization</label>
    <nameField>
        <label>Sales Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Organization_Material__c/Sales_Organization_Material__c.object-meta.xml
<CustomObject>
    <label>Sales Organization Material</label>
    <nameField>
        <label>Sales Organization Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organization Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Deletion__c.field-meta.xml
<CustomField>
    <fullName>Deletion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <label>Material Number</label>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Sales Organization Materials</relationshipLabel>
    <relationshipName>Sales_Organization_Materials</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <referenceTo>Sales_Organization__c</referenceTo>
    <relationshipLabel>Sales Organization Materials</relationshipLabel>
    <relationshipName>Sales_Organization_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_User__c/Sales_Organization_User__c.object-meta.xml
<CustomObject>
    <label>Sales Organization User</label>
    <nameField>
        <label>Sales Organization User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organization Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityLineItemTrigger_Test.cls
@isTest
public class OpportunityLineItemTrigger_Test {
    static List<Account> mAccounts;
    static User mUser;
    static List<Address__c> mShipTos;
    static List<Sales_Organization__c> mSalesOrgs;
    static List<Sales_Organization_User__c> mSalesOrgUsers;
    static List<Sales_Organization_Material__c> mSalesOrgMaterials;
    static List<Material_Number__c> mMaterials;
    static List<String> materialNumbers = new List<String>();
    static List<Product2> mNewProducts2;
    Static List<PricebookEntry> mNewPricebookEntries;
    static List<OpportunityLineItem> mNewOppLineItems ;
    static List<Opportunity> mOpportunities;
    static Id STDPriceBookId;
    static Territory2Model terrModel;
    static Territory2 objTerr;
    static List<Territory2Type> terriType;
    static List<Organization_Structure__c> mOrgStructure;
    static List<Sales_Area_Detail__c> mSalesArea;
    
    static void setupTestData(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Data Administrator'];
        mUser = new User(Alias = 'standt', Email='dataadministrator@testorg.com',
                         EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                         LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',UserName='dataadministrator@testorg.com', ERP_Id__c = 'dataadmin123');
        
        System.runAs (new User(Id = UserInfo.getUserId())){
            terriType = [SELECT id, DeveloperName from Territory2Type where DeveloperName = 'Managed_Accounts'];
            terrModel = [SELECT id, DeveloperName,State from Territory2Model where DeveloperName = 'Weir_Minerals'];
            insert objTerr = new Territory2(DeveloperName = 'TestTerritory', Territory2ModelId = terrModel.Id, Name='AM1_AM01_GB01', Territory2TypeId=terriType[0].Id);
        }
        
        Opp_Transfer_Owner__c setting = new Opp_Transfer_Owner__c();
        setting.Name = 'Test Setting';
        setting.Non_SGT_Profile__c = true;
        setting.SGT_Profile__c = true;
        insert setting;
        
        System.runAs (mUser)
        {
            STDPriceBookId = TestUtility.createSTDPriceBookRecords();
            mAccounts = TestUtility.createAccountRecords(1, True);
            mShipTos = TestUtility.createShippingRecords(1, mAccounts[0].id, True);
            mSalesOrgs = TestUtility.createSalesOrgRecords(1, 'GB01', True);
            mSalesOrgUsers = TestUtility.createSalesOrgUserRecords(1, UserInfo.getUserId(), mSalesOrgs[0].id, True);
            mOrgStructure = TestUtility.createOrgStructureRecords(1,'GB01','AM01','AM1', null, '30', '00', True, objTerr.Id, True);
            mSalesArea = TestUtility.createSalesAreaRecords(1, mAccounts[0].Id, mOrgStructure[0].id, True);
            mOpportunities = TestUtility.createOpportunityRecords(1, mAccounts[0].id, mShipTos[0].id, mSalesOrgUsers[0].id, STDPriceBookId, 'AUD','30', '00',True, True);
            mMaterials = TestUtility.createMaterialRecords(1, 'Mat123', True);
            mNewProducts2 = TestUtility.createProductRecords(1, 'Z0001S0001', True);
            mNewPricebookEntries = TestUtility.createPricebookEntryRecords(1, mNewProducts2[0].Id, STDPriceBookId,'AUD', True);
            mSalesOrgMaterials = TestUtility.createSalesOrgMaterialRecords(1, mMaterials[0].id, mSalesOrgs[0].id, False, True);
        }
    }
    
    @isTest static void MaterailValidated()
    { 
        setupTestData();
        List<Product2> mNewProducts3 = TestUtility.createProductRecords(1, 'Z0002S0002VA000001', True);
        List<PricebookEntry> mNewPricebookEntries3 = TestUtility.createPricebookEntryRecords(1, mNewProducts3[0].Id, STDPriceBookId,'AUD', True);
        mSalesOrgMaterials[0].Distribution_Channel__c = '30';
        update mSalesOrgMaterials;
        mMaterials[0].X3rd_Level_Product_Hierarchy__c = 'Z0002S0002VA000001';
        mMaterials[0].Material_Status__c = 'Active';
        update mMaterials;
        System.runAs (mUser)
        {
            mNewOppLineItems = TestUtility.createOpportunityItemRecords(1,mOpportunities[0].id,mNewProducts2[0].id,mNewPricebookEntries[0].id, mMaterials[0].id, True);
        }
    }
    
    @isTest static void MaterailDeleted()
    { 
        setupTestData();
        try
        {
            mSalesOrgMaterials[0].Deletion__c = true;
            mSalesOrgMaterials[0].Distribution_Channel__c = '30';
            update mSalesOrgMaterials;
            System.runAs (mUser)
            {
                mNewOppLineItems = TestUtility.createOpportunityItemRecords(1,mOpportunities[0].id,mNewProducts2[0].id,mNewPricebookEntries[0].id, mMaterials[0].id, True);
            }
        }
        catch(Exception e) 
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('blocked');
            System.AssertEquals(expectedExceptionThrown, true);
        } 
    }
    
    @isTest static void MaterailNotExtendtoSalesOrg()
    { 
        setupTestData();
        try
        {
            List<Material_Number__c> mMaterials1 = TestUtility.createMaterialRecords(1, 'Mat1234', True);
            System.runAs (mUser)
            {
                mNewOppLineItems = TestUtility.createOpportunityItemRecords(1,mOpportunities[0].id,mNewProducts2[0].id,mNewPricebookEntries[0].id, mMaterials1[0].id, True);
            }
        }
        catch(Exception e) 
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('is not extended');
            System.AssertEquals(expectedExceptionThrown, true);
        } 
    }
    
    @isTest static void SalesOrgUserisEmpty()
    { 
        setupTestData();
        try
        {
            mOpportunities[0].Sales_Organization_User__c = null;
            update mOpportunities;
            mNewOppLineItems = TestUtility.createOpportunityItemRecords(1,mOpportunities[0].id,mNewProducts2[0].id,mNewPricebookEntries[0].id, mMaterials[0].id, True);
        }
        catch(Exception e) 
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('Please enter');
            System.AssertEquals(expectedExceptionThrown, true);
        } 
    }
    
}