force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_ID__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Material_Number__c/Material_Number__c.object-meta.xml
<CustomObject>
    <label>Material Number</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Number</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Number__c/fields/ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_ID__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Number</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This Material is obsolete</errorMessage>
        <filterItems>
            <field>Material_Number__c.Material_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/Organization_Structure__c.object-meta.xml
<CustomObject>
    <label>Organization Structure</label>
    <nameField>
        <displayFormat>TRTY-{00000}</displayFormat>
        <label>Organization Structure Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organization Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization_Structure__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/Sales_Group__c.field-meta.xml
<CustomField>
    <fullName>Sales_Group__c</fullName>
    <label>Sales Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <label>Sales Office</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization_Structure__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Area_Detail__c/Sales_Area_Detail__c.object-meta.xml
<CustomObject>
    <label>Sales Area Detail</label>
    <nameField>
        <label>Organization Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Area Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Area_Detail__c/fields/Organization_Structure__c.field-meta.xml
<CustomField>
    <fullName>Organization_Structure__c</fullName>
    <label>Organization Structure</label>
    <referenceTo>Organization_Structure__c</referenceTo>
    <relationshipLabel>Sales Area Details</relationshipLabel>
    <relationshipName>Sales_Area_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Organization__c/Sales_Organization__c.object-meta.xml
<CustomObject>
    <label>Sales Organization</label>
    <nameField>
        <label>Sales Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Organization_Material__c/Sales_Organization_Material__c.object-meta.xml
<CustomObject>
    <label>Sales Organization Material</label>
    <nameField>
        <label>Sales Organization Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organization Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <formula>Sales_Organization__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <label>Material Number</label>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Sales Organization Materials</relationshipLabel>
    <relationshipName>Sales_Organization_Materials</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_Material__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <referenceTo>Sales_Organization__c</referenceTo>
    <relationshipLabel>Sales Organization Materials</relationshipLabel>
    <relationshipName>Sales_Organization_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_User__c/Sales_Organization_User__c.object-meta.xml
<CustomObject>
    <label>Sales Organization User</label>
    <nameField>
        <label>Sales Organization User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organization Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Organization_User__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <formula>Sales_Organizationa__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PushToSAPController_Test.cls
@isTest
public class PushToSAPController_Test {
    static List<Account> mAccounts;
    static User mUser;
    static List<Address__c> mShipTos;
    static List<Sales_Organization__c> mSalesOrgs;
    static List<Sales_Organization_User__c> mSalesOrgUsers;
    static List<Sales_Organization_Material__c> mSalesOrgMaterials;
    static List<Material_Number__c> mMaterials;
    static List<String> materialNumbers = new List<String>();
    static List<Product2> mNewProducts2;
    Static List<PricebookEntry> mNewPricebookEntries;
    static List<OpportunityLineItem> mNewOppLineItems ;
    static List<Opportunity> mOpportunities;
    static Id AccountSGTRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('SGT_Record_Type').getRecordTypeId ();
    static Id STDPriceBookId;
    static Territory2Model terrModel;
    static Territory2 objTerr;
    static List<Territory2Type> terriType;
    static List<Organization_Structure__c> mOrgStructure;
    static List<Sales_Area_Detail__c> mSalesArea;
    
    static void setupTestData(){
        
        System.runAs (new User(Id = UserInfo.getUserId())){
            terriType = [SELECT id, DeveloperName from Territory2Type where DeveloperName = 'Managed_Accounts'];
            terrModel = [SELECT id, DeveloperName,State from Territory2Model where DeveloperName = 'Weir_Minerals'];
            insert objTerr = new Territory2(DeveloperName = 'TestTerritory', Territory2ModelId = terrModel.Id, Name='AM1_AM01_GB01', Territory2TypeId=terriType[0].Id);
        }
        
        STDPriceBookId = TestUtility.createSTDPriceBookRecords();
        mSalesOrgs = TestUtility.createSalesOrgRecords(1, 'GB01', True);
        mSalesOrgUsers = TestUtility.createSalesOrgUserRecords(1, UserInfo.getUserId(), mSalesOrgs[0].id, True);
        mMaterials = TestUtility.createMaterialRecords(1, 'Mat123', True);
        mNewProducts2 = TestUtility.createProductRecords(1, 'Z0003S0012CC000001', True);
        mNewPricebookEntries = TestUtility.createPricebookEntryRecords(1, mNewProducts2[0].Id, STDPriceBookId,'AUD', True); 
        mSalesOrgMaterials = TestUtility.createSalesOrgMaterialRecords(1, mMaterials[0].id, mSalesOrgs[0].id, False, True);
        mOrgStructure = TestUtility.createOrgStructureRecords(1,'GB01','AM01','AM1', null, '30', '00', True, objTerr.Id, True);
    }
    
    @isTest static void CreateProspectAndInquiryToSAP()
    { 
        setupTestData();
        mAccounts = TestUtility.createAccountRecords1(1, null, True, True);
        mSalesArea = TestUtility.createSalesAreaRecords(1, mAccounts[0].Id, mOrgStructure[0].id, True);
        mShipTos = TestUtility.createShippingRecords(1, mAccounts[0].id, True);
        mOpportunities = TestUtility.createOpportunityRecords(1, mAccounts[0].id, mShipTos[0].id, mSalesOrgUsers[0].id, STDPriceBookId, 'AUD','30', '00',True, True);
        mNewOppLineItems = TestUtility.createOpportunityItemRecords(1,mOpportunities[0].id,mNewProducts2[0].id,mNewPricebookEntries[0].id, mMaterials[0].id, True);
        mOpportunities = [SELECT Id, Name, SGTProfile__c, StageName, Integration_Status__c, Division__c, Channel__c, CloseDate, Expected_Delivery_Date__c,CurrencyIsoCode,Opportunity_ID__c,
                          Sales_Group__c, Sales_Office__c, Territory2Id,
                          AccountId, Account.CreatedBy.profileId, Account.Name,Account.Type, Account.Industry, Account.Industry_Code__c, Account.Phone, Account.Website,
                          Account.BillingStreet, Account.BillingCity, Account.BillingState, Account.BillingStateCode, Account.BillingPostalCode, Account.BillingCountry,Account.BillingCountryCode, Shipping_Address__r.ERP_ID__c,
                          Account.Account_Status__c, Account.Prospect__c, Account.ERP_Id__c, Account.CurrencyIsoCode, Sales_Organization_User__r.code__c
                          FROM Opportunity WHERE id =: mOpportunities[0].id];

        PushToSAPController.ValidateSGTProfile(mOpportunities[0].id);
        PushToSAPController.CreateProspectAndInquiryToSAP(mOpportunities);
        
        Test.setMock(WebServiceMock.class, new CalloutSAPMock());
        Boolean result  = PushToSAP.CreateProspectAccount(mOpportunities);
        System.debug('result: '+result);
        System.assertEquals(false, result); 
    }
    
    @isTest static void CreateInquiryToSAP()
    { 
        setupTestData();
        mAccounts = TestUtility.createAccountRecords1(1, 'Acc123', True, True);
        mSalesArea = TestUtility.createSalesAreaRecords(1, mAccounts[0].Id, mOrgStructure[0].id, True);
        mShipTos = TestUtility.createShippingRecords(1, mAccounts[0].id, True);
        mOpportunities = TestUtility.createOpportunityRecords(1, mAccounts[0].id, mShipTos[0].id, mSalesOrgUsers[0].id, STDPriceBookId, 'AUD','30', '00',True, True);
        mNewOppLineItems = TestUtility.createOpportunityItemRecords(1,mOpportunities[0].id,mNewProducts2[0].id,mNewPricebookEntries[0].id, mMaterials[0].id, True);
        mOpportunities = [SELECT Id, Name, SGTProfile__c, StageName, Integration_Status__c, Division__c, Channel__c, CloseDate, Expected_Delivery_Date__c,CurrencyIsoCode,Opportunity_ID__c,
                          Sales_Group__c, Sales_Office__c, Territory2Id,        
                          AccountId, Account.CreatedBy.profileId, Account.Name,Account.Type, Account.Industry, Account.Industry_Code__c, Account.Phone, Account.Website,
                          Account.BillingStreet, Account.BillingCity, Account.BillingState, Account.BillingStateCode, Account.BillingPostalCode, Account.BillingCountry,Account.BillingCountryCode, Shipping_Address__r.ERP_ID__c,
                          Account.Account_Status__c, Account.Prospect__c, Account.ERP_Id__c, Account.CurrencyIsoCode, Sales_Organization_User__r.code__c
                          FROM Opportunity WHERE id =: mOpportunities[0].id];
        PushToSAPController.ValidateSGTProfile(mOpportunities[0].id);
        PushToSAPController.CreateProspectAndInquiryToSAP(mOpportunities);
    }
    
    @isTest static void CallOutProspectTest()
    { 
        setupTestData();
        mAccounts = TestUtility.createAccountRecords1(1, null, True, True);
        mSalesArea = TestUtility.createSalesAreaRecords(1, mAccounts[0].Id, mOrgStructure[0].id, True);
        mShipTos = TestUtility.createShippingRecords(1, mAccounts[0].id, True);
        mOpportunities = TestUtility.createOpportunityRecords(1, mAccounts[0].id, mShipTos[0].id, mSalesOrgUsers[0].id, STDPriceBookId, 'AUD','30', '00',True, True);
        mNewOppLineItems = TestUtility.createOpportunityItemRecords(1,mOpportunities[0].id,mNewProducts2[0].id,mNewPricebookEntries[0].id, mMaterials[0].id, True);
        Test.startTest();
        Test.setMock(WebServiceMock.class, new CalloutSAPMock());
        Boolean result  = PushToSAP.CreateProspectAccount(mOpportunities);
        System.assertEquals(true, result);
        
        Boolean result1  = PushToSAP.CreateInquiry(mOpportunities, mNewOppLineItems);
        System.assertEquals(true, result1);
        
        Test.stopTest();
    }
    
}