force-app/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DLV{00000000}</displayFormat>
        <label>Delivery ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Organization</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/SAP_Delivery_Order_No__c.field-meta.xml
<CustomField>
    <fullName>SAP_Delivery_Order_No__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery Created</fullName>
                <default>true</default>
                <label>Delivery Created</label>
            </value>
            <value>
                <fullName>Picking</fullName>
            </value>
            <value>
                <fullName>Packing</fullName>
            </value>
            <value>
                <fullName>Goods Issued</fullName>
            </value>
            <value>
                <fullName>Proof of Delivery</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/Delivery_Product__c.object-meta.xml
<CustomObject>
    <label>Delivery Product</label>
    <nameField>
        <displayFormat>DP{00000000}</displayFormat>
        <label>Delivery Products No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Product__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipName>Delivery_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/DO_Item_No__c.field-meta.xml
<CustomField>
    <fullName>DO_Item_No__c</fullName>
    <label>DO Item No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Item_Status__c.field-meta.xml
<CustomField>
    <fullName>Item_Status__c</fullName>
    <label>Item Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery Created</fullName>
                <default>true</default>
                <label>Delivery Created</label>
            </value>
            <value>
                <fullName>Picking</fullName>
            </value>
            <value>
                <fullName>Packing</fullName>
            </value>
            <value>
                <fullName>Goods Issued</fullName>
            </value>
            <value>
                <fullName>Proof Of Delivery</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Item_Status_Detail__c.field-meta.xml
<CustomField>
    <fullName>Item_Status_Detail__c</fullName>
    <label>Item Status Detail</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Not yet processed</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Partially processed</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Completely processed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Delivery Products</relationshipLabel>
    <relationshipName>Delivery_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Message__c/Error_Message__c.object-meta.xml
<CustomObject>
    <label>Error Message</label>
    <nameField>
        <displayFormat>ERR{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Messages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Message__c/fields/Account_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ERP_ID__c</fullName>
    <label>Account ERP ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Message__c/fields/Delivery_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Delivery_ERP_ID__c</fullName>
    <label>Delivery ERP ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Message__c/fields/Error_Message_Detail__c.field-meta.xml
<CustomField>
    <fullName>Error_Message_Detail__c</fullName>
    <label>Error Message Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Message__c/fields/Invoice_ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>Invoice_ERP_ID__c</fullName>
    <label>Invoice ERP ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Message__c/fields/Scenario__c.field-meta.xml
<CustomField>
    <fullName>Scenario__c</fullName>
    <label>Scenario</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Input Validation</fullName>
            </value>
            <value>
                <fullName>Inquiry Creation</fullName>
            </value>
            <value>
                <fullName>Indirect Quotation</fullName>
            </value>
            <value>
                <fullName>Direct Quotation</fullName>
            </value>
            <value>
                <fullName>Delta Quotation</fullName>
            </value>
            <value>
                <fullName>Indirect Sales Order</fullName>
            </value>
            <value>
                <fullName>Direct Sales Order</fullName>
            </value>
            <value>
                <fullName>Delta Sales Order</fullName>
            </value>
            <value>
                <fullName>Validation</fullName>
            </value>
            <value>
                <fullName>Account Creation</fullName>
            </value>
            <value>
                <fullName>Material Creation</fullName>
            </value>
            <value>
                <fullName>Delivery Order Creation</fullName>
            </value>
            <value>
                <fullName>Delivery Order Delta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV{0000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <label>Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_ID__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Net_Value__c.field-meta.xml
<CustomField>
    <fullName>Net_Value__c</fullName>
    <label>Net Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Organization</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Material_Number__c/Material_Number__c.object-meta.xml
<CustomObject>
    <label>Material Number</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Number</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Number__c/fields/ERP_ID__c.field-meta.xml
<CustomField>
    <fullName>ERP_ID__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Line_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_No__c</fullName>
    <label>Line Item No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Material_Number__c</description>
    <label>Material Number</label>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Created</fullName>
                <default>true</default>
                <label>Order Created</label>
            </value>
            <value>
                <fullName>Delivery In Process</fullName>
            </value>
            <value>
                <fullName>Partially Delivered</fullName>
            </value>
            <value>
                <fullName>Fully Delivered</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Organization__c/Sales_Organization__c.object-meta.xml
<CustomObject>
    <label>Sales Organization</label>
    <nameField>
        <label>Sales Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoiceDeltaWebservice.cls
global class InvoiceDeltaWebservice
{    
    global class InvoiceItem
    {
        webservice Integer invoiceLineItemNo;
        webservice String deliveryERPID;
        webservice Integer doLineItemNo;
        webservice String orderERPID; 
        webservice Integer orderLineItemNo;
        webservice String materialNumber;
        webservice String materialDescription;
        webservice Integer billedQuantity;
        webservice Decimal unitPrice;
        webservice Decimal netValue;
        webservice Decimal charges;
        webservice Decimal taxAmount;
    }
    
    global class Results
    {
        webservice boolean success;
        webservice String errorMessage;
    }
    
    public static InvoiceDeltaWebservice.Results result =  new InvoiceDeltaWebservice.Results();
    
    webservice static InvoiceDeltaWebservice.Results InvoiceDelta(
        String deliveryERPID, String accountERPID, String invoiceERPID, Date billingDate , Decimal netValue, String invoiceCurrency, String customerPONumber,
        String incoterm1, String paymentTerm, Decimal taxAmount, Decimal totalAmount, String saleOrgCode, List<InvoiceItem> InvoiceItems)
        
    {
        Id invoiceId;
        Integer invoiceItemSuccess = 0;
        Map<String,Id> orderItemsMap = new Map<String,Id>();
        Map<String,Id> deliveryItemsMap = new Map<String,Id>();
        List<String> allOrderERPIds = new List<String>();
        List<String> allDeliveryERPIds = new List<String>();
        List<OrderItem> orderItems = new List<OrderItem>();
        List<Delivery_Product__c> deliveryProducts = new List<Delivery_Product__c>();
        List<Invoice_Item__c> invoiceItemList = new List<Invoice_Item__c>();
        Map<String,InvoiceDeltaWebservice.InvoiceItem> keyInvoiceItemMap = new Map<String,InvoiceDeltaWebservice.InvoiceItem>();
        result.success = false;
        Boolean validatedItems = false;
        
        List<Invoice__c>  Invoices = [SELECT Id, Billing_Date__c, Net_Value__c, Sales_Organization__c, Sold_To__c, ERP_ID__c,
                                      (SELECT Id, Invoice_Item_No__c, Order_Item__c, Delivery_Item__c, 
                                       Invoice_Item_ID__c, Delivery_Item__r.Delivery__r.SAP_Delivery_Order_No__c, Delivery_Item__r.DO_Item_No__c, 
                                       Order_Item__r.Order.ERP_Id__c, Order_Item__r.Line_Item_No__c FROM Invoice_Items__r)
                                      FROM Invoice__c WHERE ERP_ID__c =: invoiceERPID];
        
        system.debug('accountERPID : '+accountERPID);
        List<Account> soldTo = [SELECT Id FROM Account WHERE ERP_Id__c =: accountERPID LIMIT 1];
        system.debug('soldTo : '+soldTo);
        
        if (!Invoices.isEmpty())
        {
            for(InvoiceDeltaWebservice.InvoiceItem item : InvoiceItems)
            {
                if(item.orderERPID != null) allOrderERPIds.add(item.orderERPID);
                if(item.deliveryERPID != null) allDeliveryERPIds.add(item.deliveryERPID);
            }
            
            List<OrderItem> allOrderItems = [SELECT Id, Line_Item_No__c, OrderId, Order.ERP_Id__c FROM OrderItem WHERE Order.ERP_Id__c IN: allOrderERPIds];
            List<Delivery_Product__c> allDeliveryItems = [SELECT Id, DO_Item_No__c, Delivery__r.SAP_Delivery_Order_No__c  FROM Delivery_Product__c WHERE Delivery__r.SAP_Delivery_Order_No__c IN: allDeliveryERPIds];
            
            
            system.debug('allOrderItems '+allOrderItems);
            system.debug('allDeliveryItems '+allDeliveryItems);
            for(InvoiceDeltaWebservice.InvoiceItem InvoiceItem : InvoiceItems)
            {
                validatedItems = false;
                for(OrderItem orderItem : allOrderItems)
                {
                    if(InvoiceItem.orderERPID == orderItem.Order.ERP_Id__c && InvoiceItem.orderLineItemNo == orderItem.Line_Item_No__c)
                    {
                        validatedItems = true;
                        orderItemsMap.put(InvoiceItem.orderERPID + InvoiceItem.orderLineItemNo, orderItem.Id);
                        break;
                    }
                }
                
                for(Delivery_Product__c deliveryItem : allDeliveryItems)
                {
                    if(InvoiceItem.deliveryERPID == deliveryItem.Delivery__r.SAP_Delivery_Order_No__c && InvoiceItem.doLineItemNo == deliveryItem.DO_Item_No__c)
                    {
                        deliveryItemsMap.put(InvoiceItem.deliveryERPID + InvoiceItem.doLineItemNo, deliveryItem.Id);
                        break;
                    }
                }
                
                if(validatedItems == false)
                {
                    result.errorMessage = 'Cannot find OrderItem No. '+ InvoiceItem.orderLineItemNo+' orderERPID: '+InvoiceItem.orderERPID;
                    System.debug(result.errorMessage);
                    createErrorMessage(result.errorMessage, deliveryERPID, accountERPID, invoiceERPID);
                    break;
                }
            }
            
            system.debug('orderItemsMap : '+orderItemsMap);
            system.debug('deliveryItemsMap : '+deliveryItemsMap);
            
            
            List<Delivery__c>  Deliveries = [SELECT Id, Status__c, Sales_Organization__c, 
                                             (SELECT Id, Delivery__c, Item_Status__c, Item_Status_Detail__c, Order_Product__c, Order_Product__r.Order.ERP_Id__c 
                                              FROM Delivery_Orders__r)  FROM Delivery__c WHERE SAP_Delivery_Order_No__c =: deliveryERPID];
            
            if (validatedItems == true)
            { 
                Savepoint sp = Database.setSavepoint(); 
                //-----------Create Invoice__c------------------//
                Invoice__c invoice = new Invoice__c ();
                invoice.Id = Invoices[0].Id;
                invoice.Billing_Date__c  = billingDate;
                invoice.Net_Value__c  = netValue;
                invoice.Sales_Organization__c  = saleOrgCode;
                invoice.ERP_ID__c  = invoiceERPID;
                invoice.CurrencyIsoCode = invoiceCurrency;
                if(!soldTo.isEmpty()) invoice.Sold_To__c = soldTo[0].Id;
                invoice.Customer_PO_Number__c  = customerPONumber;
                invoice.Payment_Term__c = paymentTerm;
                invoice.Incoterm_1__c = incoterm1;
                invoice.Tax_Amount__c = taxAmount;
                invoice.Total_Amount__c = totalAmount;
                
                system.debug('update invoice '+invoice);
                Database.SaveResult invoiceResult = Database.update(invoice, false);
                if (invoiceResult.isSuccess())
                {
                    invoiceId = invoiceResult.getId();
                    System.debug('Invoice updated successfully: ' + invoiceId);
                    
                    //-----------Update Invoice Line Items------------------//
                    if (!InvoiceItems.isEmpty())
                    { 
                        for(InvoiceDeltaWebservice.InvoiceItem item : InvoiceItems)
                        { 
                            Invoice_Item__c invoiceItem = new Invoice_Item__c();
                            invoiceItem.Invoice__c = invoiceId;
                            invoiceItem.Invoice_Item_No__c = item.invoiceLineItemNo;
                            if(deliveryItemsMap.get(item.deliveryERPID + item.doLineItemNo) != null)
                                invoiceItem.Delivery_Item__c = deliveryItemsMap.get(item.deliveryERPID + item.doLineItemNo);
                            if(orderItemsMap.get(item.orderERPID + item.orderLineItemNo) != null)
                                invoiceItem.Order_Item__c = orderItemsMap.get(item.orderERPID + item.orderLineItemNo);
                            invoiceItem.Billed_Quantity__c = item.billedQuantity;
                            invoiceItem.Material_Number__c = item.materialNumber;
                            invoiceItem.Product_Description__c = item.materialDescription;
                            invoiceItem.Net_Value__c = item.netValue;
                            invoiceItem.Unit_Price__c = item.unitPrice;
                            invoiceItem.Charges__c = item.charges;
                            invoiceItem.Tax_Amount__c = item.taxAmount;
                            invoiceItem.CurrencyIsoCode = invoiceCurrency;
                            invoiceItem.Invoice_Item_ID__c = invoiceERPID + item.invoiceLineItemNo;
                            invoiceItemList.add(invoiceItem);
                        }
                        
                        if(!invoiceItemList.isEmpty())
                        {
                            Schema.SObjectField ftoken = Invoice_Item__c.Fields.Invoice_Item_ID__c;
                            Database.UpsertResult[] invoiceItemResultList = Database.upsert(invoiceItemList,ftoken,false);
                            for (Database.UpsertResult sr : invoiceItemResultList) 
                            {
                                if (sr.isSuccess())
                                {
                                    invoiceItemSuccess = invoiceItemSuccess+1;
                                    System.debug('InvoiceItems updated successfully: ' + sr.getId());
                                }
                                else
                                {              
                                    for(Database.Error err : sr.getErrors())
                                    {                 
                                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                                        System.debug('InvoiceItems fields that affected this error: ' + err.getFields());
                                        result.errorMessage = 'Update InvoiceItems '+err.getStatusCode() + ': ' + err.getMessage();
                                    }
                                    Database.rollback(sp);
                                    createErrorMessage(result.errorMessage, deliveryERPID, accountERPID, invoiceERPID);
                                }
                            }
                            
                            if(invoiceItemSuccess == invoiceItemList.size())
                            {
                                Delivery__c delivery;
                                if(deliveryERPID != null && deliveryERPID != '')
                                {
                                    //-----------Update Delivery_Product__c------------------//
                                    for(Delivery_Product__c dItem : Deliveries[0].Delivery_Orders__r)
                                    {
                                        Delivery_Product__c deliveryProduct = new Delivery_Product__c();
                                        deliveryProduct.Id = dItem.Id;
                                        deliveryProduct.Item_Status__c = 'Billing';
                                        deliveryProduct.Item_Status_Detail__c = 'c';
                                        deliveryProducts.add(deliveryProduct);
                                        
                                        OrderItem oItem = new OrderItem();
                                        oItem.Id = dItem.Order_Product__c;
                                        oItem.Status__c = 'Billing';
                                        orderItems.add(oItem);
                                    }
                                    
                                    delivery = new Delivery__c(Id = Deliveries[0].Id, Status__c = 'Billing');
                                    
                                }
                                else
                                {
                                    for(OrderItem item : allOrderItems)
                                    {
                                        OrderItem oItem = new OrderItem();
                                        oItem.Id = item.Id;
                                        oItem.Status__c = 'Billing';
                                        oItem.Without_Delivery__c = true;
                                        orderItems.add(oItem);
                                    }
                                }
                                
                                try
                                {
                                    if(deliveryERPID != null && deliveryERPID != ''){
                                        update delivery;
                                        update deliveryProducts;
                                    }
                                    
                                    update orderItems;
                                    result.success = true;
                                }
                                catch (DmlException e)
                                {
                                    System.debug(e.getMessage() + ': ' + e.getLineNumber());
                                }
                            }
                        } 
                    } 
                }
                else // Update Invoice Fail
                {              
                    for(Database.Error err : invoiceResult.getErrors())
                    {                 
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Invoice fields that affected this error: ' + err.getFields());
                        result.errorMessage = 'Update Invoice '+err.getStatusCode() + ': ' + err.getMessage();
                    }
                    Database.rollback(sp);
                    createErrorMessage(result.errorMessage, deliveryERPID, accountERPID, invoiceERPID);
                }
                
            }
        }            
        System.debug('ReturnValue '+result);
        return result;  
        
    }
    
    public static void createErrorMessage(String errMessage, String deliveryERPID, String accountERPID, String invoiceERPID)
    {
        try
        {
            Error_Message__c mError = new Error_Message__c();
            mError.Scenario__c = 'Invoice Delta';
            mError.Error_Message_Detail__c = errMessage;
            mError.Delivery_ERP_ID__c = deliveryERPID;
            mError.Account_ERP_ID__c = accountERPID;
            mError.Invoice_ERP_ID__c = invoiceERPID;
            insert mError;
        }
        catch (DmlException e)
        {
            System.debug(e.getMessage() + ': ' + e.getLineNumber());
        }
    }
}