force-app/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DLV{00000000}</displayFormat>
        <label>Delivery ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery__c/fields/Planned_Good_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Good_Issue_Date__c</fullName>
    <label>Planned Good Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/SAP_Delivery_Order_No__c.field-meta.xml
<CustomField>
    <fullName>SAP_Delivery_Order_No__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery Created</fullName>
                <default>true</default>
                <label>Delivery Created</label>
            </value>
            <value>
                <fullName>Picking</fullName>
            </value>
            <value>
                <fullName>Packing</fullName>
            </value>
            <value>
                <fullName>Goods Issued</fullName>
            </value>
            <value>
                <fullName>Proof of Delivery</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Status_Detail__c.field-meta.xml
<CustomField>
    <fullName>Status_Detail__c</fullName>
    <label>Status Detail</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Not yet processed</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Partially processed</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Completely processed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Tracking_No__c.field-meta.xml
<CustomField>
    <fullName>Tracking_No__c</fullName>
    <label>Tracking No.</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/Delivery_Product__c.object-meta.xml
<CustomObject>
    <label>Delivery Product</label>
    <nameField>
        <displayFormat>DP{00000000}</displayFormat>
        <label>Delivery Products No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Product__c/fields/Actual_Goods_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Goods_Issue_Date__c</fullName>
    <label>Actual Goods Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipName>Delivery_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Delivery_Qty__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Qty__c</fullName>
    <label>Quantity to Deliver</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Delivery_Qty_UOM__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Qty_UOM__c</fullName>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SAP_Measurement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/DO_Item_No__c.field-meta.xml
<CustomField>
    <fullName>DO_Item_No__c</fullName>
    <label>DO Item No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Gross_Weight__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Item_Status__c.field-meta.xml
<CustomField>
    <fullName>Item_Status__c</fullName>
    <label>Item Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery Created</fullName>
                <default>true</default>
                <label>Delivery Created</label>
            </value>
            <value>
                <fullName>Picking</fullName>
            </value>
            <value>
                <fullName>Packing</fullName>
            </value>
            <value>
                <fullName>Goods Issued</fullName>
            </value>
            <value>
                <fullName>Proof Of Delivery</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Item_Status_Detail__c.field-meta.xml
<CustomField>
    <fullName>Item_Status_Detail__c</fullName>
    <label>Item Status Detail</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <default>true</default>
                <label>Not yet processed</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Partially processed</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Completely processed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Net_Weight__c.field-meta.xml
<CustomField>
    <fullName>Net_Weight__c</fullName>
    <label>Net Weight</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Order_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Order_Item_No__c</fullName>
    <label>Order Item No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Delivery Products</relationshipLabel>
    <relationshipName>Delivery_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Planned_Goods_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Goods_Issue_Date__c</fullName>
    <label>Planned Goods Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <label>Material Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Actual_Goods_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Goods_Issue_Date__c</fullName>
    <description>Latest Actual Goods Issue Date</description>
    <inlineHelpText>Latest Actual Goods Issue Date</inlineHelpText>
    <label>Actual Goods Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Material_Description__c.field-meta.xml
<CustomField>
    <fullName>Material_Description__c</fullName>
    <formula>Material_Number__r.Material_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Created</fullName>
                <default>true</default>
                <label>Order Created</label>
            </value>
            <value>
                <fullName>Delivery In Process</fullName>
            </value>
            <value>
                <fullName>Partially Delivered</fullName>
            </value>
            <value>
                <fullName>Fully Delivered</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/SAP_Measurement.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue><fullName>P1</fullName><label>%</label></customValue>
<customValue><fullName>2M</fullName><label>CMS</label></customValue>
<customValue><fullName>2X</fullName><label>000</label></customValue>
<customValue><fullName>4G</fullName><label>µL</label></customValue>
<customValue><fullName>4O</fullName><label>µF</label></customValue>
<customValue><fullName>4T</fullName><label>IB</label></customValue>
<customValue><fullName>AMP</fullName><label>A</label></customValue>
<customValue><fullName>A87</fullName><label>GOH</label></customValue>
<customValue><fullName>A93</fullName><label>GM3</label></customValue>
<customValue><fullName>W08</fullName><label>ADH</label></customValue>
<customValue><fullName>WE3</fullName><label>AFS</label></customValue>
<customValue><fullName>B34</fullName><label>KD3</label></customValue>
<customValue><fullName>B45</fullName><label>QML</label></customValue>
<customValue><fullName>B47</fullName><label>NI</label></customValue>
<customValue><fullName>B73</fullName><label>MN</label></customValue>
<customValue><fullName>B75</fullName><label>MGO</label></customValue>
<customValue><fullName>B78</fullName><label>MHV</label></customValue>
<customValue><fullName>B84</fullName><label>µA</label></customValue>
<customValue><fullName>BG</fullName><label>BAG</label></customValue>
<customValue><fullName>BAR</fullName><label>BAR</label></customValue>
<customValue><fullName>BO</fullName><label>BT</label></customValue>
<customValue><fullName>BOX</fullName><label>BOX</label></customValue>
<customValue><fullName>BYT</fullName><label>BYT</label></customValue>
<customValue><fullName>C10</fullName><label>RF</label></customValue>
<customValue><fullName>C38</fullName><label>M/L</label></customValue>
<customValue><fullName>C39</fullName><label>NA</label></customValue>
<customValue><fullName>2J</fullName><label>C3S</label></customValue>
<customValue><fullName>C41</fullName><label>R-U</label></customValue>
<customValue><fullName>C56</fullName><label>NMM</label></customValue>
<customValue><fullName>CMQ</fullName><label>CCM</label></customValue>
    <masterLabel>SAP Measurement</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderDeliveryController.cls
public without sharing class OrderDeliveryController 
{
    @AuraEnabled
    public static List<Delivery__c> getOrderDetails(Id recordId) 
    {
        Set<Id> DeliveryIds = new Set<Id>();
        List<Delivery_Product__c> deliveryItems = [SELECT Id, Name, Delivery__c FROM Delivery_Product__c WHERE Order_Product__r.OrderId =: recordId];
        for(Delivery_Product__c item : deliveryItems)
        {
            DeliveryIds.add(item.Delivery__c);
        }
        
        List<Delivery__c> delivery = [SELECT Id, SAP_Delivery_Order_No__c, Planned_Good_Issue_Date__c, Status__c, Status_Detail__c,Carrier_Name__c,Tracking_No__c,
                                      (SELECT Id, Name, Delivery_Qty__c, Planned_Goods_Issue_Date__c, Actual_Goods_Issue_Date__c, Order_Product__c, Item_Status__c, 
                                       Item_Status_Detail__c, DO_Item_No__c, Order_Item_No__c, Order_Product__r.Material_Description__c, Product_ID__c, Product_Description__c, 
                                       Delivery_Qty_UOM__c, Order_Product__r.Quantity, Gross_Weight__c,Net_Weight__c
                                       FROM Delivery_Orders__r WHERE Order_Product__r.OrderId =: recordId Order by CreatedDate)
                                      FROM Delivery__c WHERE Id IN: DeliveryIds];
        
        system.debug('delivery '+delivery.size());
        
        //delivery = removeEmptyDelivery(delivery);
        
        return delivery;
        
    }
        
    @AuraEnabled
    public static List<Delivery__c> getOrderItemDetails(Id recordId) 
    {
        
        Set<Id> DeliveryIds = new Set<Id>();
        List<Delivery_Product__c> deliveryItems = [SELECT Id, Name, Delivery__c FROM Delivery_Product__c WHERE Order_Product__c =: recordId];
        for(Delivery_Product__c item : deliveryItems)
        {
            DeliveryIds.add(item.Delivery__c);
        }
        
        List<Delivery__c> delivery = [SELECT Id, SAP_Delivery_Order_No__c, Planned_Good_Issue_Date__c, Status__c, Status_Detail__c,Carrier_Name__c,Tracking_No__c,
                                      (SELECT Id, Name, Delivery_Qty__c, Planned_Goods_Issue_Date__c, Actual_Goods_Issue_Date__c, Order_Product__c, Item_Status__c, 
                                       Item_Status_Detail__c, DO_Item_No__c, Order_Item_No__c, Order_Product__r.Material_Description__c, Product_ID__c, Product_Description__c, 
                                       Delivery_Qty_UOM__c, Order_Product__r.Quantity, Gross_Weight__c,Net_Weight__c
                                       FROM Delivery_Orders__r WHERE Order_Product__c =: recordId Order by CreatedDate)
                                      FROM Delivery__c WHERE Id IN: DeliveryIds];
        
        system.debug('delivery '+delivery.size());
        
        //delivery = removeEmptyDelivery(delivery);
        
        return delivery;
        
    }
    
    /*public static List<Delivery__c> removeEmptyDelivery(List<Delivery__c> delivery)
    {
        List<Delivery__c> newDelivery = new List<Delivery__c>();
        system.debug('Before '+delivery.size());
        for(Delivery__c o : delivery)
        {
            //system.debug(o);
            if(!o.Delivery_Orders__r.isEmpty())
            {
                newDelivery.add(o);
            }
        }
        system.debug('After '+newDelivery.size());
        
        return newDelivery;
    }*/
}