force-app/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DLV{00000000}</displayFormat>
        <label>Delivery ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Organization</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/SAP_Delivery_Order_No__c.field-meta.xml
<CustomField>
    <fullName>SAP_Delivery_Order_No__c</fullName>
    <externalId>true</externalId>
    <label>ERP ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/Delivery_Product__c.object-meta.xml
<CustomObject>
    <label>Delivery Product</label>
    <nameField>
        <displayFormat>DP{00000000}</displayFormat>
        <label>Delivery Products No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Product__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipName>Delivery_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Order_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Order_Item_No__c</fullName>
    <label>Order Item No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Product__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Delivery Products</relationshipLabel>
    <relationshipName>Delivery_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Material_Number__c/Material_Number__c.object-meta.xml
<CustomObject>
    <label>Material Number</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Material Number</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem/fields/Line_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_No__c</fullName>
    <label>Line Item No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Material_Number__c</description>
    <label>Material Number</label>
    <referenceTo>Material_Number__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Organization__c/Sales_Organization__c.object-meta.xml
<CustomObject>
    <label>Sales Organization</label>
    <nameField>
        <label>Sales Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderDeliveryControllerTest.cls
@isTest
public class OrderDeliveryControllerTest 
{
    @TestSetup
    static void setupData()
    {
        Id STDPriceBookId = TestUtility.createSTDPriceBookRecords();
        List<Product2> products = TestUtility.createProductRecords(1, 'Z0001S0001', True);
        List<PricebookEntry> pbes = TestUtility.createPricebookEntryRecords(1, products[0].Id, STDPriceBookId,'AUD', True);
        List<Material_Number__c> materials = TestUtility.createMaterialRecords(1, 'Mat123', True);
        List<Account> accounts = TestUtility.createAccountRecords(1, TRUE);
        Order ord = new Order();
        ord.Pricebook2Id = STDPriceBookId;
        ord.CurrencyIsoCode = 'AUD';
        ord.AccountId = accounts.get(0).Id;
        ord.Status = 'Draft';
        ord.EffectiveDate = System.today();      
        insert ord;
        
        Delivery__c delivery = new Delivery__c();
        delivery.SAP_Delivery_Order_No__c = '6000020345';
        delivery.Sales_Organization__c = 'GB01';
        delivery.Account__c = accounts.get(0).Id;
        insert delivery;
        
        List<OrderItem> mNeworderItems = new List<OrderItem>();
        OrderItem mNewOrderItem = new OrderItem();
        mNewOrderItem.OrderId = ord.Id;
        mNewOrderItem.PricebookEntryId = pbes.get(0).Id;
        mNewOrderItem.Product2Id = products.get(0).Id;
        mNewOrderItem.Material_Number__c = materials.get(0).Id;
        mNewOrderItem.Quantity = 2;
        mNewOrderItem.UnitPrice = 10;
        mNewOrderItem.Line_Item_No__c = 10;
        mNeworderItems.add(mNewOrderItem);
        insert mNeworderItems;
        
        List<Delivery_Product__c> deliveryItems = new List<Delivery_Product__c>();
        Delivery_Product__c deliveryItem = new Delivery_Product__c();
        deliveryItem.Order_Item_No__c = 10;
        deliveryItem.Order_Product__c = mNeworderItems.get(0).Id;
        deliveryItem.Delivery__c = delivery.Id;
        deliveryItems.add(deliveryItem);
        insert deliveryItems;
    }

    @isTest
    static void testGetOrderDeliveryItems() {
      
        Id orderId = [SELECT Id FROM Order].Id;
        Id orderItemId = [SELECT Id FROM OrderItem].Id; 

        
        Test.startTest();
        OrderDeliveryController.getOrderDetails(orderId);
        OrderDeliveryController.getOrderItemDetails(orderItemId);
        Test.stopTest();

    }     
    
}