force-app/main/default/objects/Sales_Organization__c/Sales_Organization__c.object-meta.xml
<CustomObject>
    <label>Sales Organization</label>
    <nameField>
        <label>Sales Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organizations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Organization__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Organizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_User__c/Sales_Organization_User__c.object-meta.xml
<CustomObject>
    <label>Sales Organization User</label>
    <nameField>
        <label>Sales Organization User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organization Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Organization_User__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <formula>Sales_Organizationa__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_User__c/fields/Sales_Organizationa__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organizationa__c</fullName>
    <label>Sales Organization</label>
    <referenceTo>Sales_Organization__c</referenceTo>
    <relationshipLabel>Sales Organization Users (Sales Organizationa)</relationshipLabel>
    <relationshipName>Sales_Organization_Users1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Organization_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Organization_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestOpportunityCreation.cls
@isTest
public class TestOpportunityCreation {
    
    static testmethod void SetupData()
    {
        Account acct = new Account(Name='Test Account',BillingCity='BillingCity',BillingPostalCode='BillingPostalCode',BillingCountry ='BillingCountry');
        insert acct;
        Sales_Organization__c SaleOrg = new Sales_Organization__c(Name='Asia Commercial',Code__c='MY03');
        insert SaleOrg;
        Sales_Organization_User__c SaleOrgUser = new Sales_Organization_User__c(Name='TestSalesOrgUser',User__c=UserInfo.getUserId(),Sales_Organizationa__c=SaleOrg.id);
        insert SaleOrgUser;
        Opportunity opp = new Opportunity(Name='Opportunity Name',OwnerId = UserInfo.getUserId(), StageName='Qualification',CloseDate=System.today().addMonths(1),AccountId=acct.Id);
        insert opp;
    }
}