force-app/main/default/objects/Object_Permission__c/Object_Permission__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Object related permission settings - Custom Account deletion setting.</description>
    <label>Object - Permission</label>
</CustomObject>

force-app/main/default/objects/Object_Permission__c/fields/Account_Delete_Prospect__c.field-meta.xml
<CustomField>
    <fullName>Account_Delete_Prospect__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Allow deletion of Prospect Accounts.</inlineHelpText>
    <label>Account Delete Prospect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The customer account that owns and is responsible for the project</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Account__c/Project_Account__c.object-meta.xml
<CustomObject>
    <label>Project Account Connection</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Account Connections</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects Involved</relationshipLabel>
    <relationshipName>Project_Account_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Account__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts Involved</relationshipLabel>
    <relationshipName>Project_Account_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTest.cls
@isTest
public class AccountTest 
{
    @testSetup
    static void setupData()
    {
    	Object_Permission__c objectPermission = new Object_Permission__c();
        objectPermission.Account_Delete_Prospect__c = TRUE;
        insert objectPermission;
    }
    
	@isTest
    static void testDeleteProspectAccountWithDeletePermission()
    {
        Account account = new Account(Name = 'Test', BillingCity = 'Kuala Lumpur', BillingPostalCode = '12345', BillingCountry = 'Malaysia');
        account.Prospect__c = true;
        insert account;
        
        Test.startTest();
        delete account;
        Test.stopTest();
        
        List<Account> accounts = [SELECT Id FROM Account WHERE Name = 'Test'];
        System.assertEquals(0, accounts.size(), 'Prospect Account should be allowed to be deleted.');
    }
    
	@isTest
    static void testDeleteProspectAccountWithoutDeletePermission()
    {
        Object_Permission__c objectPermission = Object_Permission__c.getInstance();
        objectPermission.Account_Delete_Prospect__c = FALSE;
        upsert objectPermission;
        
        Account account = new Account(Name = 'Test', BillingCity = 'Kuala Lumpur', BillingPostalCode = '12345', BillingCountry = 'Malaysia');
        account.Prospect__c = true;
        insert account;
        
        Test.startTest();
        try
        {
            delete account;
        }
        catch (Exception e)
        {
            System.debug(e);
        }        
        Test.stopTest();
        
        List<Account> accounts = [SELECT Id FROM Account WHERE Name = 'Test'];
        System.assertEquals(1, accounts.size(), 'Prospect Account should not be allowed to be deleted.');
    }    
    
	@isTest
    static void testDeleteNonProspectAccountWithoutDeletePermission()
    {
        Account account = new Account(Name = 'Test', BillingCity = 'Kuala Lumpur', BillingPostalCode = '12345', BillingCountry = 'Malaysia');        
        account.Prospect__c = false;
        insert account;
        
        Test.startTest();
        try
        {
        	delete account;
        }
        catch(Exception e)
        {
            System.debug(e);
        }
        Test.stopTest();
        
        List<Account> accounts = [SELECT Id FROM Account WHERE Name = 'Test'];
        System.assertEquals(1, accounts.size(), 'Non Prospect Account should not be allowed to be deleted.');        
    }
    
    @isTest
    static void testDeleteAccount()
    {
        Account account = new Account(Name = 'Test', BillingCity = 'Kuala Lumpur', BillingPostalCode = '12345', BillingCountry = 'Malaysia');
        insert account;
        Project__c project = new Project__c(Name = 'PROJECT_NAME', Account__c = account.Id);
        insert project; 
        Project_Account__c mProjectAccount = new Project_Account__c(Account__c = account.Id , Project__c = project.Id);
        insert mProjectAccount;
        
        Test.startTest();
        delete account;
        Test.stopTest();
    }    
}