force-app/main/default/objects/Object_Permission__c/Object_Permission__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Object related permission settings - Custom Account deletion setting.</description>
    <label>Object - Permission</label>
</CustomObject>

force-app/main/default/objects/Object_Permission__c/fields/Account_Delete_Non_Prospect__c.field-meta.xml
<CustomField>
    <fullName>Account_Delete_Non_Prospect__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Allow deletion of Non-Prospect Accounts.</inlineHelpText>
    <label>Account Delete Non Prospect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Object_Permission__c/fields/Account_Delete_Prospect__c.field-meta.xml
<CustomField>
    <fullName>Account_Delete_Prospect__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Allow deletion of Prospect Accounts.</inlineHelpText>
    <label>Account Delete Prospect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The customer account that owns and is responsible for the project</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ERP_Id__c.field-meta.xml
<CustomField>
    <fullName>ERP_Id__c</fullName>
    <externalId>true</externalId>
    <label>ERP Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project_Account__c/Project_Account__c.object-meta.xml
<CustomObject>
    <label>Project Account Connection</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Account Connections</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects Involved</relationshipLabel>
    <relationshipName>Project_Account_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Account__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts Involved</relationshipLabel>
    <relationshipName>Project_Account_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountController.cls
public without sharing class AccountController 
{
	private static Object_Permission__c objectPermission = Object_Permission__c.getInstance();
    
    public static void validateDelete(List<Account> accounts)
    {
        for (Account account : accounts)
        {
            if (account.Prospect__c == TRUE && account.ERP_Id__c == NULL && objectPermission.Account_Delete_Prospect__c == FALSE)
            {
                account.addError(System.Label.Delete_Error);
            }
            else if (((account.Prospect__c == TRUE && account.ERP_Id__c != NULL ) || account.Prospect__c == FALSE) && objectPermission.Account_Delete_Non_Prospect__c == FALSE)
            {
                account.addError(System.Label.Delete_Error);
            }
        }
    }
    
    public static void deleteChildRecords(Set<Id> accounts)
    {
        //system.debug('accounts : '+accounts);
        List<Project_Account__c> projectAccounts = new  List<Project_Account__c>();
        for(Project_Account__c projectAccount :[SELECT Id, Name, Project__c, Account__c FROM Project_Account__c where Account__c IN: accounts])
            projectAccounts.add(projectAccount);
        if(!projectAccounts.isEmpty())
            delete projectAccounts;

    }
}